#!/usr/bin/env python3
"""AUTO-PLAN (§159) — auto-maintains, on a schedule:
 1. full pending enumeration (every item + count)        [§158]
 2. an ordered build plan (next_pending queue)            [§105]
 3. cron-coverage check (registered jobs vs recurring needs)
Writes jobs/reports/auto_plan.md + auto_plan.json. Building still needs operator 'go'
(a cron cannot write features); this keeps the PLAN + PENDING current with zero prompts."""
import json, subprocess, sys
from datetime import datetime, timezone
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
REP = ROOT / "jobs" / "reports"


def load(p):
    try: return json.loads((ROOT / p).read_text())
    except Exception: return {}


def main():
    now = datetime.now(timezone.utc).astimezone().strftime("%Y-%m-%d %H:%M %Z")
    # refresh STATUS first
    subprocess.run([sys.executable, str(ROOT / "scripts" / "status_report.py")],
                   capture_output=True, cwd=ROOT, timeout=60)

    # 1. full pending enumeration
    pend = []
    pend += [f"CDM: {t['name']} [{t['status']}]" for t in load('config/data_manager.json').get('tasks', []) if t['status'] != 'built']
    pend += [f"Dashboard: {t['name']} [{t['status']}]" for t in load('config/expert_dashboards.json').get('dashboards', []) if t['status'] != 'built']
    for r in load('config/expert_roles.json').get('roles', []):
        pend += [f"Role/{r['role'].split('(')[0].strip()}: {t['name']} [{t['status']}]" for t in r['tasks'] if t['status'] != 'built']
    pend += [f"Ecosystem: {t['name']} [planned]" for c in load('config/neuro_ai_ecosystem.json').get('categories', []) for t in c['tools'] if t['status'] == 'planned']
    pend += [f"Lib: {t['name']} [cataloged]" for L in load('config/eeg_ai_stack.json').get('layers', []) for t in L['tools'] if t['status'] == 'cataloged']

    # 2. ordered build plan
    try:
        import importlib.util
        spec = importlib.util.spec_from_file_location("np", ROOT / "scripts" / "next_pending.py")
        np_mod = importlib.util.module_from_spec(spec); spec.loader.exec_module(np_mod)
        queue = np_mod.BUILDABLE
    except Exception:
        queue = []

    # 3. cron coverage
    jobs = load('config/jobs.json').get('jobs', [])
    crons = subprocess.run("crontab -l", shell=True, capture_output=True, text=True).stdout
    job_status = [{"id": j["id"], "tag": j["cron_tag"], "installed": j["cron_tag"] in crons} for j in jobs]
    missing_cron = [j["id"] for j in job_status if not j["installed"]]

    # write markdown plan
    md = [f"# 🤖 AUTO-PLAN — {now}",
          f"> Auto-generated by scripts/auto_plan.py (AUTO-PLAN cron). Building needs operator 'go'.\n",
          f"## ⏳ Pending: {len(pend)} items\n"]
    for i, p in enumerate(pend, 1):
        md.append(f"{i}. {p}")
    md.append(f"\n## ▸ Ordered build plan (next {len(queue)})\n")
    for i, q in enumerate(queue, 1):
        md.append(f"{i}. [{q['value']}/{q['effort']}] {q['title']}")
    md.append(f"\n## ⏰ Cron coverage ({sum(j['installed'] for j in job_status)}/{len(job_status)} installed)\n")
    for j in job_status:
        md.append(f"- {'✅' if j['installed'] else '❌ MISSING'} {j['id']} ({j['tag']})")
    if missing_cron:
        md.append(f"\n⚠ Missing crons to install: {', '.join(missing_cron)}")
    md.append("\n## 🔒 Blocked / 🔴 Gated\n- Blocked: Gmail/Slack/Drive creds · auth · EMR/FHIR\n- Gated: push commits · ictal/interictal retrain")
    REP.mkdir(parents=True, exist_ok=True)
    (REP / "auto_plan.md").write_text("\n".join(md) + "\n")
    (REP / "auto_plan.json").write_text(json.dumps(
        {"generated": now, "pending_count": len(pend), "queue": queue,
         "cron_coverage": job_status, "missing_cron": missing_cron}, indent=2))
    print(f"AUTO-PLAN: {len(pend)} pending · {len(queue)} queued · crons {sum(j['installed'] for j in job_status)}/{len(job_status)} installed"
          + (f" · MISSING: {missing_cron}" if missing_cron else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
