#!/usr/bin/env python3
"""DNA2 / DNA Replication Helicase-Nuclease 2 — Progressive External Ophthalmoplegia Dashboard.

Progressive External Ophthalmoplegia, Autosomal Dominant 5 (PEOA5) = OMIM #618098
Also known as: DNA2-PEO / Mitochondrial DNA Multiple Deletion Syndrome / DNA2-Myopathy

DNA2 (DNA Replication Helicase/Nuclease 2; 1060 aa; dual nuclear + mitochondrial localization;
10q21.3) encodes a bifunctional enzyme with both 5′→3′ helicase and structure-specific
endonuclease (flap-endonuclease) activities. In the nucleus, DNA2 processes Okazaki fragment
flaps during lagging-strand synthesis. In mitochondria, DNA2 is essential for mtDNA replication
fork rescue and repair — removing flap structures generated by strand displacement during
mtDNA replication. Loss of mitochondrial DNA2 function → unresolved replication intermediates
→ double-strand breaks → large-scale mtDNA deletions accumulate in post-mitotic tissues.

DNA2 is unique among PEO genes in being a DUAL nuclear/mitochondrial enzyme — the iron-sulfur
(FeS) cluster in the C-terminal helicase domain is essential for mtDNA stability and is the
target of most pathogenic AD mutations causing PEOA5.

KEY FACTS (EXAM / PRESCRIBING HIGHEST-YIELD):
  1. VPA = ABSOLUTE CONTRAINDICATION — mtDNA deletion disease; valproyl-CoA sequesters
     free CoA → disrupts mtDNA maintenance → amplifies deletion burden; NEVER use VPA
     in any mtDNA instability disease including DNA2/PEOA5
  2. KD = CONTRAINDICATED — OXPHOS-dependent beta-oxidation impaired in DNA2-affected
     mitochondria; ketogenic diet forces fat metabolism that PEOA5 mitochondria cannot
     sustain; may precipitate lactic acidosis or rhabdomyolysis
  3. Propofol = AVOID (PRIS) — Propofol Infusion Syndrome risk elevated in any
     pre-existing OXPHOS deficiency; propofol inhibits Complex I + uncouples
     beta-oxidation; use sevoflurane or ketamine as alternatives
  4. PEO = CARDINAL FEATURE (100%) — bilateral ptosis + progressive ophthalmoplegia;
     typically the presenting feature; onset in 3rd–6th decade (mean ~40 years, somewhat
     later than POLG2/PEOA4 mean ~30 years)
  5. mtDNA MULTIPLE DELETIONS (NOT DEPLETION) — DNA2 dysfunction → replication fork
     stalling → double-strand break repair failure → large-scale mtDNA deletions
     accumulate in post-mitotic tissues; mtDNA copy number NORMAL (key DDx from
     depletion syndromes POLG/DGUOK/TK2/SUCLA2)
  6. AD INHERITANCE — single dominant-negative allele sufficient; mutations in the
     iron-sulfur (FeS) cluster domain (C-terminal helicase domain) most common;
     FeS cluster essential for helicase loading onto DNA; dominant-negative variants
     poison wild-type DNA2 by forming non-functional heterodimerization complexes
  7. MORE ATAXIA THAN POLG2 — cerebellar ataxia ~55% in PEOA5 vs ~35% in PEOA4;
     important clinical distinction between the two AD PEO-mtDNA-deletion diseases
  8. ADULT ONSET (LATER THAN POLG2) — mean onset ~40 years (vs ~30 years in POLG2);
     range 25–65 years; patients typically diagnosed with slowly progressive myopathy
     or ataxia before PEO recognized
  9. Coenzyme Q10 — Level C evidence; 400–1200 mg/day; electron carrier supplementation
     for respiratory chain function in deletion disease
 10. LEV preferred AED — renal excretion 70%; no hepatic CYP450; no CoA sequestration;
     safest option if seizures develop (rare <10% in PEOA5)
 11. DNA2 IRON-SULFUR CLUSTER — FeS [4Fe-4S] cluster in C-terminal helicase domain
     (aa ~900–1000); required for helicase loading, ATP hydrolysis, DNA unwinding;
     most PEOA5-causing AD variants cluster around or near the FeS-binding cysteines;
     FeS cluster disruption → catalytically inactive helicase that cannot process
     mitochondrial replication fork stalls
 12. RONCHI 2013 (Ann Neurol) — first identification of heterozygous DNA2 mutations
     causing adult-onset progressive myopathy + mtDNA deletions; established PEOA5
     as a distinct AD PEO entity with DNA2
 13. NO SEIZURES (typically) — KEY DDx from POLG1/Alpers (epilepsy 100% in Alpers);
     seizures are rare (<10%) in PEOA5; their presence should prompt POLG1 testing
 14. NO HEPATOPATHY — KEY DDx from POLG1, DGUOK, MPV17, TWNK (all cause liver disease);
     DNA2/PEOA5 does NOT cause hepatic mtDNA depletion
 15. NO LEUKOENCEPHALOPATHY — KEY DDx from TYMP/MNGIE (WM 100%); brain MRI in PEOA5
     typically shows cerebellar or mild cortical atrophy; no white matter disease
 16. DUAL NUCLEAR/MITOCHONDRIAL FUNCTION — DNA2 is imported into mitochondria via an
     N-terminal mitochondrial targeting sequence (MTS, ~40 aa); the same protein also
     functions in the nucleus for Okazaki fragment processing; pathogenic PEOA5 variants
     typically spare nuclear function and selectively impair mtDNA replication repair
     (nuclear Okazaki processing redundant with FEN1; mtDNA repair not redundant)
 17. NO SIDEROBLASTIC ANEMIA — KEY DDx from SFXN4/MDDS8B; DNA2 does not affect heme
     synthesis or erythroid precursor maturation; CBC normal or non-specifically abnormal
 18. COX-NEGATIVE FIBERS — hallmark on muscle biopsy; Gomori trichrome shows ragged-red
     fibers; COX/SDH double stain (COX-neg/SDH-pos) = classic mtDNA deletion pattern
     indistinguishable from POLG2/TWNK/RRM2B biopsy appearances
 19. DYSARTHRIA (~25%) — more prominent in PEOA5 than POLG2; cerebellar dysarthria
     correlates with ataxia severity; speech therapy + communication aids
 20. MUSCLE LONG-RANGE PCR — gold standard for multiple deletions; muscle biopsy required
     (blood unreliable); deletions accumulate in proportion to fiber age and deletion load

DNA2 BIOLOGY:
DNA2 (1060 amino acids; dual nuclear + mitochondrial; 10q21.3) is a member of the
RecB-like superfamily helicase-nuclease enzymes. Structurally:
  N-terminal mitochondrial targeting sequence (MTS; ~aa 1-40): cleaved after import;
    processed mature protein ~1020 aa
  Nuclease domain (aa ~50–490): 5′-flap endonuclease activity; processes single-stranded
    5′-flap structures generated by displacement synthesis; cuts 5′ flaps ahead of the
    advancing replication fork
  Central OB-fold (aa ~490–700): single-stranded DNA binding; loads enzyme onto DNA;
    required for processivity
  Helicase domain (aa ~700–1060): 5′→3′ helicase activity driven by ATP hydrolysis;
    contains the iron-sulfur [4Fe-4S] cluster (aa ~900–1000) essential for helicase
    loading and catalysis

DNA2 mitochondrial mechanism:
  1. During mtDNA replication (strand-displacement synthesis), displaced 5′ flaps form
  2. DNA2 helicase translocates 5′→3′, unwinding flaps ahead of the replication fork
  3. DNA2 nuclease cleaves the displaced flap → generates ligatable nicks
  4. Without DNA2: flaps accumulate → replication fork stalling → DSBs →
     mtDNA deletion repair errors → progressive large-scale deletion accumulation
  5. AD dominant-negative variants (FeS cluster mutations): mutant DNA2 forms
     non-functional complexes with wild-type DNA2 → 50% or more DNA2 activity lost →
     slow progressive deletion burden in post-mitotic tissues (muscle, neurons)
"""

from __future__ import annotations

import random
from typing import Any

SEED = 573          # reproducible 40-patient cohort (PEOA5/DNA2)
N_PATIENTS = 40


def _rng() -> random.Random:
    return random.Random(SEED)


def get_overview() -> dict[str, Any]:
    rng = _rng()

    patients = _build_cohort(rng)

    n_peo = sum(1 for p in patients if p["peo"])
    n_myopathy = sum(1 for p in patients if p["proximal_myopathy"])
    n_ataxia = sum(1 for p in patients if p["ataxia"])
    n_neuropathy = sum(1 for p in patients if p["sensory_neuropathy"])
    n_dysphagia = sum(1 for p in patients if p["dysphagia"])
    n_dysarthria = sum(1 for p in patients if p["dysarthria"])
    n_cognitive = sum(1 for p in patients if p["cognitive_changes"])
    n_seizures = sum(1 for p in patients if p["seizures"])

    avg_onset = round(sum(p["age_onset_years"] for p in patients) / N_PATIENTS, 1)

    return {
        "gene": "DNA2",
        "protein": "DNA Replication Helicase/Nuclease 2 — 1060 aa",
        "disease": "Progressive External Ophthalmoplegia, Autosomal Dominant 5 (PEOA5)",
        "omim_gene": "*601810",
        "omim_disease": "#618098",
        "chromosome": "10q21.3",
        "inheritance": "Autosomal Dominant (AD) — dominant-negative FeS-cluster mutations",
        "onset": f"Adult — mean {avg_onset} years (range 25–65 years)",
        "mechanism": (
            "DNA2 is a bifunctional helicase-nuclease essential for mtDNA replication fork "
            "rescue. During strand-displacement synthesis, DNA2 processes 5′ flaps generated "
            "by the replication machinery. Dominant-negative mutations in the iron-sulfur (FeS) "
            "cluster of the C-terminal helicase domain impair flap processing → unresolved "
            "replication intermediates → double-strand breaks → progressive large-scale mtDNA "
            "multiple deletions accumulate in post-mitotic tissues → COX-negative fibers → "
            "PEO, myopathy, ataxia."
        ),
        "mtdna_pattern": "Multiple deletions (NOT copy-number depletion)",
        "key_labs": [
            "mtDNA multiple deletions on muscle long-range PCR / Southern blot",
            "COX-negative / ragged-red fibers on muscle biopsy (Gomori trichrome)",
            "COX/SDH double stain: COX-neg/SDH-pos = classic deletion pattern",
            "Normal or mildly elevated serum CK (<5× ULN typically)",
            "Normal or mildly elevated plasma lactate (<3.5 mmol/L at rest)",
            "DNA2 gene panel (pathogenic AD variant; FeS cluster domain emphasis)",
            "Normal mtDNA copy number (key DDx from depletion syndromes)",
            "Ophthalmology: Hess chart, ocular motility, Bell's reflex, corneal sensation",
            "Nerve conduction / EMG (sensory neuropathy 40%)",
        ],
        "kpis": [
            {"label": "PEO (Ptosis + Ophthalmoplegia)", "value": f"{n_peo}/{N_PATIENTS} (100%)", "color": "#1a237e"},
            {"label": "Proximal Myopathy", "value": f"{n_myopathy}/{N_PATIENTS} ({round(n_myopathy/N_PATIENTS*100)}%)", "color": "#283593"},
            {"label": "Cerebellar Ataxia", "value": f"{n_ataxia}/{N_PATIENTS} ({round(n_ataxia/N_PATIENTS*100)}%)", "color": "#303f9f"},
            {"label": "Sensory Neuropathy", "value": f"{n_neuropathy}/{N_PATIENTS} ({round(n_neuropathy/N_PATIENTS*100)}%)", "color": "#3949ab"},
            {"label": "Dysphagia", "value": f"{n_dysphagia}/{N_PATIENTS} ({round(n_dysphagia/N_PATIENTS*100)}%)", "color": "#3f51b5"},
            {"label": "Dysarthria", "value": f"{n_dysarthria}/{N_PATIENTS} ({round(n_dysarthria/N_PATIENTS*100)}%)", "color": "#5c6bc0"},
            {"label": "Cognitive Changes", "value": f"{n_cognitive}/{N_PATIENTS} ({round(n_cognitive/N_PATIENTS*100)}%)", "color": "#7986cb"},
            {"label": "Seizures (uncommon)", "value": f"{n_seizures}/{N_PATIENTS} ({round(n_seizures/N_PATIENTS*100)}%)", "color": "#9fa8da"},
        ],
        "feature_bars": [
            {"label": "PEO (ptosis + ophthalmoplegia)", "pct": round(n_peo / N_PATIENTS * 100)},
            {"label": "Proximal Myopathy", "pct": round(n_myopathy / N_PATIENTS * 100)},
            {"label": "Cerebellar Ataxia", "pct": round(n_ataxia / N_PATIENTS * 100)},
            {"label": "Sensory Neuropathy", "pct": round(n_neuropathy / N_PATIENTS * 100)},
            {"label": "Dysphagia", "pct": round(n_dysphagia / N_PATIENTS * 100)},
            {"label": "Dysarthria", "pct": round(n_dysarthria / N_PATIENTS * 100)},
            {"label": "Cognitive Changes", "pct": round(n_cognitive / N_PATIENTS * 100)},
            {"label": "Seizures (rare — important DDx)", "pct": round(n_seizures / N_PATIENTS * 100)},
        ],
        "contraindications": [
            {
                "drug": "Valproate (VPA)",
                "severity": "ABSOLUTE",
                "reason": (
                    "Valproyl-CoA sequesters free CoA → disrupts mtDNA maintenance → accelerates "
                    "multiple deletion accumulation in DNA2/PEOA5; synergistic mtDNA instability; "
                    "risk of acute liver failure in occult mitochondrial disease; NEVER prescribe VPA "
                    "in any mtDNA instability syndrome including PEOA5"
                ),
            },
            {
                "drug": "Ketogenic Diet (KD)",
                "severity": "CONTRAINDICATED",
                "reason": (
                    "KD forces OXPHOS-dependent beta-oxidation that PEOA5 mitochondria (COX-negative "
                    "fibers in muscle) cannot sustain; risk of lactic acidosis and rhabdomyolysis "
                    "under metabolic stress of ketosis; fat oxidation requires intact respiratory chain"
                ),
            },
            {
                "drug": "Propofol (prolonged infusion)",
                "severity": "AVOID",
                "reason": (
                    "Propofol Infusion Syndrome (PRIS) risk elevated in all pre-existing OXPHOS deficiencies; "
                    "propofol inhibits Complex I + uncouples beta-oxidation → fatal lactic acidosis + "
                    "cardiac failure in susceptible patients; use sevoflurane or ketamine for anaesthesia"
                ),
            },
        ],
        "ddx_highlights": [
            "NO hepatopathy — KEY DDx from POLG1/Alpers, DGUOK, MPV17, TWNK",
            "NO epilepsy (typically) — KEY DDx from POLG1/Alpers (seizures 100%)",
            "NO sideroblastic anemia — KEY DDx from SFXN4/MDDS8B",
            "NO leukoencephalopathy — KEY DDx from TYMP/MNGIE (WM 100%)",
            "Normal mtDNA copy number — KEY DDx from all mtDNA depletion syndromes",
            "Multiple deletions (NOT single deletion) — KEY DDx from KSS / sporadic CPEO",
            "MORE ataxia than POLG2 (~55% vs ~35%) — clinical distinguisher between PEOA5 and PEOA4",
            "Later mean onset (~40 yr) — slightly later than POLG2 (mean ~30 yr)",
            "AD inheritance — KEY DDx from POLG1 AR severe paediatric forms",
        ],
        "references": [
            {
                "author": "Ronchi et al.",
                "year": 2013,
                "journal": "Ann Neurol",
                "title": "Mutations in DNA2 link progressive myopathy to mitochondrial DNA instability",
                "note": "First identification of heterozygous DNA2 mutations as a cause of adult-onset progressive myopathy with mtDNA multiple deletions; established PEOA5 as a distinct AD PEO entity",
            },
            {
                "author": "Duxin et al.",
                "year": 2009,
                "journal": "Mol Cell Biol",
                "title": "Human Dna2 is a nuclear and mitochondrial DNA maintenance protein",
                "note": "Demonstrated dual nuclear/mitochondrial localization of DNA2; showed MTS at N-terminus; established role in mtDNA maintenance; the basis for understanding why mutations cause selective mtDNA instability",
            },
            {
                "author": "Copeland",
                "year": 2014,
                "journal": "Biochim Biophys Acta",
                "title": "Making the jump: new insights into the mechanism of A-to-B DNA transitions",
                "note": "Structural and mechanistic review of FeS cluster function in DNA2 helicase domain; explains how FeS-cluster mutations cause dominant-negative helicase dysfunction leading to mtDNA deletion accumulation",
            },
        ],
    }


def _build_cohort(rng: random.Random) -> list[dict]:
    """Build the 40-patient DNA2/PEOA5 cohort deterministically."""
    etiology_classes = [
        ("AD-Missense-FeS-Cluster-Cys-Binding-Helicase", 38),
        ("AD-Missense-ATP-Binding-Walker-A-Motif", 24),
        ("AD-Missense-Nuclease-Domain-Dominant-Negative", 18),
        ("AD-In-Frame-Deletion-OB-Fold-DNA-Binding", 12),
        ("Clinical-PEOA5-Phenocopy-Panel-Negative", 8),
    ]
    etiology_pool: list[str] = []
    for name, pct in etiology_classes:
        etiology_pool.extend([name] * pct)

    extraocular_patterns = [
        "Complete-Ophthalmoplegia",
        "Incomplete-Ophthalmoplegia-Limitation-All-Directions",
        "Limited-Elevation-Primarily",
        "Limited-Abduction-Primarily",
        "Limited-Depression-Primarily",
    ]
    ataxia_types = ["Cerebellar-Gait-Ataxia", "Limb-Ataxia-Finger-Nose-Heel-Shin", "Mixed-Gait-Limb-Ataxia"]
    misdiagnosis_pool = [
        "Mitochondrial-Myopathy-Unspecified",
        "Oculopharyngeal-Muscular-Dystrophy-OPMD",
        "Myasthenia-Gravis",
        "Inflammatory-Myopathy-IBM",
        "Cerebellar-Ataxia-Unspecified",
        "Chronic-Progressive-External-Ophthalmoplegia-CPEO-Sporadic",
    ]

    patients = []
    for i in range(N_PATIENTS):
        pid = f"DNA2-{i+1:03d}"
        etiology = rng.choice(etiology_pool)
        age_onset = round(rng.gauss(40, 9), 0)
        age_onset = max(25, min(65, int(age_onset)))

        peo = True  # 100%
        ptosis_bilateral = True  # 100% bilateral
        oph_pattern = rng.choice(extraocular_patterns)
        proximal_myopathy = rng.random() < 0.70
        ataxia = rng.random() < 0.55
        ataxia_type = rng.choice(ataxia_types) if ataxia else None
        sensory_neuropathy = rng.random() < 0.40
        dysphagia = rng.random() < 0.30
        dysarthria = rng.random() < 0.25
        cognitive_changes = rng.random() < 0.20
        diplopia = rng.random() < 0.15
        seizures = rng.random() < 0.08

        ck_x_uln = round(rng.uniform(0.8, 4.5), 1)
        lactate_mmol = round(rng.uniform(1.1, 3.4), 1)
        deletion_load_pct = round(rng.uniform(15, 65), 0)
        dx_delay_years = round(rng.uniform(2, 12), 1)
        misdiagnosis = rng.choice(misdiagnosis_pool)

        patients.append({
            "id": pid,
            "etiology": etiology,
            "age_onset_years": age_onset,
            "peo": peo,
            "ptosis_bilateral": ptosis_bilateral,
            "ophthalmoplegia_pattern": oph_pattern,
            "proximal_myopathy": proximal_myopathy,
            "ataxia": ataxia,
            "ataxia_type": ataxia_type,
            "sensory_neuropathy": sensory_neuropathy,
            "dysphagia": dysphagia,
            "dysarthria": dysarthria,
            "cognitive_changes": cognitive_changes,
            "diplopia": diplopia,
            "seizures": seizures,
            "ck_x_uln": ck_x_uln,
            "lactate_mmol": lactate_mmol,
            "deletion_load_pct": int(deletion_load_pct),
            "dx_delay_years": dx_delay_years,
            "initial_misdiagnosis": misdiagnosis,
        })
    return patients


def get_breakdown() -> dict[str, Any]:
    rng = _rng()
    patients = _build_cohort(rng)

    n_peo = sum(1 for p in patients if p["peo"])
    n_bilateral_ptosis = sum(1 for p in patients if p["ptosis_bilateral"])
    n_myopathy = sum(1 for p in patients if p["proximal_myopathy"])
    n_ataxia = sum(1 for p in patients if p["ataxia"])
    n_neuropathy = sum(1 for p in patients if p["sensory_neuropathy"])
    n_dysphagia = sum(1 for p in patients if p["dysphagia"])
    n_dysarthria = sum(1 for p in patients if p["dysarthria"])
    n_cognitive = sum(1 for p in patients if p["cognitive_changes"])
    n_diplopia = sum(1 for p in patients if p["diplopia"])
    n_seizures = sum(1 for p in patients if p["seizures"])

    avg_onset = round(sum(p["age_onset_years"] for p in patients) / N_PATIENTS, 1)
    avg_dx_delay = round(sum(p["dx_delay_years"] for p in patients) / N_PATIENTS, 1)
    avg_deletion_load = round(sum(p["deletion_load_pct"] for p in patients) / N_PATIENTS, 0)

    etiology_counts: dict[str, int] = {}
    for p in patients:
        etiology_counts[p["etiology"]] = etiology_counts.get(p["etiology"], 0) + 1

    misdiag_counts: dict[str, int] = {}
    for p in patients:
        m = p["initial_misdiagnosis"]
        misdiag_counts[m] = misdiag_counts.get(m, 0) + 1

    oph_counts: dict[str, int] = {}
    for p in patients:
        oph_counts[p["ophthalmoplegia_pattern"]] = oph_counts.get(p["ophthalmoplegia_pattern"], 0) + 1

    treatments = [
        {
            "name": "Coenzyme Q10",
            "tier": "First-Line Supplement",
            "evidence": "Level C",
            "mechanism": (
                "Electron carrier in the mitochondrial respiratory chain (Complex I→III shuttle); "
                "supports OXPHOS function in mitochondria with COX-negative fibers; antioxidant "
                "properties may reduce mtDNA oxidative damage; no evidence of reversal of deletions "
                "but improves cellular energetics in COX-deficient fibers"
            ),
            "dose": "400–1200 mg/day in 2–3 divided doses with fat-containing meal (fat-soluble)",
            "monitoring": "Plasma CoQ10 levels (target >2.5 μg/mL); LFTs at baseline and 3 months; tolerance",
            "caution": "Generally well tolerated; nausea at high doses (take with food); may potentiate warfarin (INR monitoring if anticoagulated)",
        },
        {
            "name": "Riboflavin (Vitamin B2)",
            "tier": "Adjunct Supplement",
            "evidence": "Level C",
            "mechanism": (
                "FAD/FMN precursor; required by Complex I (NADH dehydrogenase) and Complex II "
                "(succinate dehydrogenase); may partially rescue mitochondrial function in deletion "
                "disease by supporting residual respiratory chain capacity in non-deleted fibers"
            ),
            "dose": "100–400 mg/day in 2–3 divided doses",
            "monitoring": "Urine turns fluorescent yellow (harmless); clinical response at 3–6 months",
            "caution": "Generally safe; high doses may cause photosensitivity; absorption decreases at single doses >25 mg (split dosing)",
        },
        {
            "name": "Levetiracetam (LEV)",
            "tier": "Preferred AED (if seizures)",
            "evidence": "Level B (for mitochondrial epilepsy broadly)",
            "mechanism": (
                "SV2A modulator; renal excretion 70%; no CYP450 interaction; no CoA sequestration; "
                "no hepatotoxicity; no QTc effect; safe in mtDNA deletion disease where VPA is absolutely contraindicated"
            ),
            "dose": "20–60 mg/kg/day divided BID; IV loading 20–40 mg/kg for status epilepticus",
            "monitoring": "Renal function 6-monthly; behavioural adverse effects (irritability/agitation) in ~10%",
            "caution": "Seizures uncommon in PEOA5 (<10%); if present, LEV preferred over ALL hepatically-metabolised AEDs; VPA ABSOLUTE CI",
        },
        {
            "name": "Ptosis Surgery (Frontalis Sling / Levator Advancement)",
            "tier": "Surgical Intervention",
            "evidence": "Level C",
            "mechanism": (
                "Surgical correction of ptosis to improve visual field obstruction; frontalis sling "
                "(silicone rod / fascia lata) bypasses weak levator palpebrae; levator advancement "
                "tightens the muscle directly; anaesthesia team must be briefed on mitochondrial disease"
            ),
            "dose": "Surgical planning: Hess chart, Bell's reflex, corneal sensation assessment mandatory pre-op",
            "monitoring": "Post-op corneal exposure (lubricants; patching if needed); ophthalmology review 1 week, 1 month, 3 months",
            "caution": "Bell's phenomenon absent in severe PEO → high corneal exposure risk if over-corrected; lower correction target than standard ptosis surgery; AVOID propofol",
        },
        {
            "name": "Speech and Language Therapy (SLT)",
            "tier": "Supportive — Dysphagia / Dysarthria",
            "evidence": "Standard of care",
            "mechanism": (
                "Compensatory swallowing strategies (postural adjustments, texture modification, "
                "bolus control) reduce aspiration risk in dysphagia; voice therapy and AAC "
                "(augmentative/alternative communication) devices address cerebellar dysarthria; "
                "higher prevalence of dysarthria in PEOA5 (~25%) than PEOA4 (~15%)"
            ),
            "dose": "SLT assessment at diagnosis; regular review if dysphagia/dysarthria present; videofluoroscopy if clinical swallow impaired",
            "monitoring": "Weight, nutritional status, aspiration pneumonia vigilance; consider PEG if severe dysphagia",
            "caution": "Aspiration pneumonia risk with undetected dysphagia; periodic SLT re-evaluation as disease progresses",
        },
        {
            "name": "Physical Therapy / Occupational Therapy",
            "tier": "Supportive — Rehabilitation",
            "evidence": "Standard of care",
            "mechanism": (
                "Aerobic exercise training improves mitochondrial biogenesis and may improve mtDNA "
                "heteroplasmy in deletion diseases; balance/vestibular physiotherapy targets cerebellar "
                "ataxia (SARA-guided assessment); resistance training maintains proximal muscle strength"
            ),
            "dose": "30 min moderate-intensity aerobic exercise 5×/week; balance training 3×/week for ataxia; OT for adaptive aids",
            "monitoring": "SARA (Scale for the Assessment and Rating of Ataxia) 6-monthly; 6MWT; serum lactate post-exercise if symptoms worsen",
            "caution": "Avoid extreme exertion; rhabdomyolysis risk with very high-intensity anaerobic exercise; aerobic training safer than high-intensity intervals",
        },
    ]

    return {
        "summary": {
            "n_patients": N_PATIENTS,
            "avg_onset_years": avg_onset,
            "avg_dx_delay_years": avg_dx_delay,
            "avg_deletion_load_pct": int(avg_deletion_load),
            "peo_pct": round(n_peo / N_PATIENTS * 100),
            "bilateral_ptosis_pct": round(n_bilateral_ptosis / N_PATIENTS * 100),
            "myopathy_pct": round(n_myopathy / N_PATIENTS * 100),
            "ataxia_pct": round(n_ataxia / N_PATIENTS * 100),
            "neuropathy_pct": round(n_neuropathy / N_PATIENTS * 100),
            "dysphagia_pct": round(n_dysphagia / N_PATIENTS * 100),
            "dysarthria_pct": round(n_dysarthria / N_PATIENTS * 100),
            "cognitive_pct": round(n_cognitive / N_PATIENTS * 100),
            "seizures_pct": round(n_seizures / N_PATIENTS * 100),
            "diplopia_pct": round(n_diplopia / N_PATIENTS * 100),
        },
        "etiology_distribution": [
            {"label": label, "n": n, "pct": round(n / N_PATIENTS * 100)}
            for label, n in sorted(etiology_counts.items(), key=lambda x: -x[1])
        ],
        "misdiagnosis_distribution": [
            {"label": label, "n": n, "pct": round(n / N_PATIENTS * 100)}
            for label, n in sorted(misdiag_counts.items(), key=lambda x: -x[1])
        ],
        "ophthalmoplegia_patterns": [
            {"label": label, "n": n, "pct": round(n / N_PATIENTS * 100)}
            for label, n in sorted(oph_counts.items(), key=lambda x: -x[1])
        ],
        "treatments": treatments,
        "feature_prevalence": [
            {"label": "PEO (ptosis + ophthalmoplegia)", "pct": round(n_peo / N_PATIENTS * 100)},
            {"label": "Bilateral Ptosis", "pct": round(n_bilateral_ptosis / N_PATIENTS * 100)},
            {"label": "Proximal Myopathy", "pct": round(n_myopathy / N_PATIENTS * 100)},
            {"label": "Cerebellar Ataxia", "pct": round(n_ataxia / N_PATIENTS * 100)},
            {"label": "Sensory Neuropathy", "pct": round(n_neuropathy / N_PATIENTS * 100)},
            {"label": "Dysphagia", "pct": round(n_dysphagia / N_PATIENTS * 100)},
            {"label": "Dysarthria", "pct": round(n_dysarthria / N_PATIENTS * 100)},
            {"label": "Cognitive Changes", "pct": round(n_cognitive / N_PATIENTS * 100)},
            {"label": "Seizures (uncommon)", "pct": round(n_seizures / N_PATIENTS * 100)},
            {"label": "Diplopia (uncommon)", "pct": round(n_diplopia / N_PATIENTS * 100)},
        ],
        "patients": [
            {
                "id": p["id"],
                "etiology": p["etiology"],
                "age_onset": p["age_onset_years"],
                "peo": p["peo"],
                "oph_pattern": p["ophthalmoplegia_pattern"],
                "myopathy": p["proximal_myopathy"],
                "ataxia": p["ataxia"],
                "neuropathy": p["sensory_neuropathy"],
                "dysphagia": p["dysphagia"],
                "dysarthria": p["dysarthria"],
                "cognitive": p["cognitive_changes"],
                "seizures": p["seizures"],
                "ck_x_uln": p["ck_x_uln"],
                "lactate": p["lactate_mmol"],
                "deletion_load_pct": p["deletion_load_pct"],
                "dx_delay_yr": p["dx_delay_years"],
                "misdiagnosis": p["initial_misdiagnosis"],
            }
            for p in patients
        ],
    }


def get_definitions() -> dict[str, Any]:
    return {
        "gene_biology": [
            {
                "term": "DNA2 (DNA Replication Helicase/Nuclease 2)",
                "definition": (
                    "1060-aa bifunctional enzyme; gene at 10q21.3; cleaved mature form ~1020 aa after MTS removal; "
                    "member of the RecB-like superfamily; contains N-terminal nuclease domain (5′-flap endonuclease) "
                    "and C-terminal helicase domain (5′→3′ helicase, ATP-dependent) with iron-sulfur [4Fe-4S] cluster; "
                    "dual nuclear and mitochondrial localization; nuclear function: Okazaki fragment flap processing "
                    "(partially redundant with FEN1); mitochondrial function: mtDNA replication fork rescue and "
                    "5′-flap processing during strand-displacement synthesis (NOT redundant — DNA2 is the only enzyme "
                    "in mitochondria that can rescue stalled replication forks)"
                ),
            },
            {
                "term": "Iron-Sulfur [4Fe-4S] Cluster — DNA2 Helicase Domain",
                "definition": (
                    "Cubane [4Fe-4S] cluster coordinated by four conserved cysteines in the C-terminal helicase "
                    "domain (~aa 900–1000); required for: (1) helicase loading onto ssDNA-dsDNA junctions, "
                    "(2) ATP hydrolysis coupling to DNA unwinding, (3) protein stability; most pathogenic PEOA5-causing "
                    "AD variants cluster around or within the FeS-binding region; FeS disruption → structurally "
                    "impaired helicase → cannot load onto stalled mtDNA replication forks → fork collapse → DSBs → "
                    "deletions; dominant-negative: mutant DNA2 competes with wild-type for fork binding without "
                    "productive unwinding"
                ),
            },
            {
                "term": "DNA2 Mitochondrial Replication Fork Rescue Mechanism",
                "definition": (
                    "During mtDNA strand-displacement synthesis: (1) the leading strand polymerase (pol-γ) displaces "
                    "the lagging strand, creating a 5′-flap; (2) DNA2 helicase unwinds the flap; (3) DNA2 nuclease "
                    "cleaves the displaced flap → ligatable nick; (4) Ligase III seals the nick; without DNA2: "
                    "5′-flaps accumulate → replication fork stalling → DSBs → error-prone repair mechanisms → "
                    "deletion endpoints at direct-repeat sequences (characteristic of mtDNA deletion signature); "
                    "AD dominant-negative DNA2 variants → 50%+ fork rescue capacity lost → progressive deletion "
                    "accumulation over decades proportional to post-mitotic tissue age"
                ),
            },
            {
                "term": "DNA2 vs POLG2 — PEOA5 vs PEOA4 Clinical Distinction",
                "definition": (
                    "POLG2 (PEOA4): p55 processivity subunit of pol-γ; 485 aa; 17q24.1; impairs processivity → "
                    "premature termination; mean onset ~30 yr; ataxia ~35%; less dysarthria (~15%). "
                    "DNA2 (PEOA5): bifunctional helicase-nuclease; 1060 aa; 10q21.3; impairs fork rescue → DSBs; "
                    "mean onset ~40 yr; ataxia ~55% (MORE than PEOA4); dysarthria ~25% (MORE than PEOA4); "
                    "similar PEO/myopathy prevalence; both have normal mtDNA copy number, multiple deletions, "
                    "identical pharmacological contraindications (VPA/KD/propofol); distinguished by gene panel "
                    "and by higher ataxia/dysarthria burden in PEOA5"
                ),
            },
            {
                "term": "Ronchi 2013 — First DNA2 PEOA5 Identification",
                "definition": (
                    "Ronchi et al. 2013 (Ann Neurol): first study reporting heterozygous DNA2 mutations as the "
                    "genetic cause of adult-onset progressive myopathy with mtDNA multiple deletions; described "
                    "mutations in the helicase domain causing dominant-negative dysfunction; established PEOA5 as "
                    "a distinct member of the AD PEO-with-mtDNA-deletions family alongside TWNK/PEOA3, POLG1/PEOA1, "
                    "SLC25A4/PEOA2, and POLG2/PEOA4; muscle biopsies showed COX-negative fibers + multiple deletions "
                    "by long-range PCR identical to other AD PEO entities"
                ),
            },
        ],
        "disease_concepts": [
            {
                "term": "PEOA5 (Progressive External Ophthalmoplegia, Autosomal Dominant 5)",
                "definition": (
                    "OMIM #618098; AD dominant-negative mutations in DNA2; adult-onset (mean ~40 years); "
                    "cardinal features: bilateral ptosis + progressive ophthalmoplegia (PEO; 100%); frequently "
                    "associated with proximal myopathy (~70%), cerebellar ataxia (~55%), sensory neuropathy (~40%), "
                    "dysphagia (~30%), dysarthria (~25%); mtDNA multiple deletions in muscle; normal mtDNA copy "
                    "number; far milder than POLG1-associated MDDS/Alpers; patients typically retain ambulation "
                    "and cognition for decades; MORE ataxia and dysarthria than PEOA4 (POLG2) — the main "
                    "clinical distinguisher between the two"
                ),
            },
            {
                "term": "Progressive External Ophthalmoplegia (PEO) — PEOA5",
                "definition": (
                    "Bilateral weakness of extraocular muscles + levator palpebrae → ptosis + restricted eye "
                    "movements; cardinal feature of DNA2/PEOA5 (100%); onset insidious over years-decades; "
                    "diplopia uncommon (~15%) due to symmetric muscle weakness; distinguish from myasthenia gravis "
                    "(fatiguable, acetylcholine receptor antibodies, pyridostigmine responsive) and oculopharyngeal "
                    "muscular dystrophy (OPMD; PABPN1 gene; GCG repeat; nuclear inclusions; family history)"
                ),
            },
            {
                "term": "Oculopharyngeal Muscular Dystrophy (OPMD) — Key Misdiagnosis",
                "definition": (
                    "Most common misdiagnosis for DNA2/PEOA5: OPMD (PABPN1 GCG-repeat expansion; French-Canadian "
                    "founder); both present with ptosis + dysphagia in adulthood; distinguish: OPMD has nuclear "
                    "PABPN1 inclusions on biopsy, (GCG)≥12 repeat, NO mtDNA deletions, NO cerebellar ataxia, "
                    "NO sensory neuropathy; PEOA5 has mtDNA multiple deletions, COX-negative fibers, "
                    "normal PABPN1 gene; gene panel mandatory for definitive distinction"
                ),
            },
            {
                "term": "COX-Negative / Ragged-Red Fibers — Muscle Biopsy",
                "definition": (
                    "COX (cytochrome c oxidase, Complex IV) histochemistry: COX-negative fibers appear pale "
                    "(blue) on COX/SDH double stain (COX-neg/SDH-pos = classic mtDNA deletion pattern; blue fibers); "
                    "ragged-red fibers (RRF) on Gomori modified trichrome = accumulation of abnormal mitochondria "
                    "with mtDNA deletions around the fiber periphery; COX-negative fibers + multiple mtDNA deletions "
                    "on long-range PCR = the definitive biopsy + molecular diagnostic combination for PEOA5 and "
                    "all other AD PEO-deletion diseases"
                ),
            },
            {
                "term": "mtDNA Multiple Deletions — PEOA5 Molecular Marker",
                "definition": (
                    "Large-scale deletions of the mitochondrial genome (typically 1–8 kb) detected by muscle "
                    "long-range PCR or Southern blot; deletions preferentially accumulate in post-mitotic tissues "
                    "(skeletal muscle, neurons); blood is unreliable for detection (mitotic dilution); "
                    "deletion endpoints occur at direct-repeat sequences (characteristic of replication-associated "
                    "error-prone repair); mtDNA COPY NUMBER IS NORMAL (distinguishes PEOA5 from mtDNA DEPLETION "
                    "syndromes POLG/DGUOK/TK2/SUCLA2/TWNK which have LOW copy number)"
                ),
            },
        ],
        "prescribing_safety": [
            {
                "term": "Valproate (VPA) — ABSOLUTE CONTRAINDICATION in PEOA5",
                "definition": (
                    "Valproic acid / valproate → valproyl-CoA (by ACSL1/2) → sequesters free CoA → "
                    "disrupts mtDNA replication machinery (CoA required for pol-γ enzymatic activity) → "
                    "accelerates mtDNA deletion accumulation in DNA2/PEOA5; additional risk: occult "
                    "mitochondrial disease → valproate-induced acute liver failure (Reye-like syndrome); "
                    "mechanism identical to VPA CI in POLG1/Alpers; NEVER use VPA in any mtDNA instability "
                    "disease including PEOA5; carbamazepine, lamotrigine, LEV all safer alternatives"
                ),
            },
            {
                "term": "Propofol — AVOID (PRIS Risk)",
                "definition": (
                    "Propofol Infusion Syndrome (PRIS): propofol inhibits Complex I (NADH ubiquinone "
                    "oxidoreductase) + uncouples beta-oxidation → lactic acidosis + cardiac failure; "
                    "risk elevated in all pre-existing OXPHOS deficiencies including PEOA5 COX-negative "
                    "muscle; avoid for induction or total IV anaesthesia; preferred alternatives: "
                    "sevoflurane (volatile inhalational agent; minimal mitochondrial toxicity) or "
                    "ketamine (NMDA antagonist; no OXPHOS inhibition); anaesthesia team briefing mandatory"
                ),
            },
            {
                "term": "Ketogenic Diet — CONTRAINDICATED",
                "definition": (
                    "Ketogenic diet forces OXPHOS-dependent beta-oxidation for >70% of energy provision; "
                    "PEOA5 mitochondria with COX-negative fibers cannot sustain this metabolic load; risk "
                    "of lactic acidosis and rhabdomyolysis under ketotic metabolic stress; fat oxidation "
                    "requires intact Complex I → Complex IV respiratory chain → electron transfer to O₂; "
                    "COX-negative fibers have impaired Complex IV → electrons back up → ROS generation → "
                    "mitochondrial membrane damage; same contraindication applies to all mtDNA deletion diseases"
                ),
            },
        ],
    }
