"""
MMN (Mismatch Negativity) Dashboard — NeuroAI EEG
==================================================
Pre-attentive auditory memory ERP analysis: MMN and P3a peak latency/amplitude
from a passive 2-tone auditory oddball paradigm. Data is derived deterministically
from real patient demographics in clinical.db.

The MMN is a negative ERP deflection maximal at Fz/FCz, peaking at 100–200 ms
post-deviant stimulus. It is generated by a pre-attentive auditory change detection
mechanism in the auditory cortex (primary and secondary) that does not require
attention or active cooperation from the patient.

Key distinguishing feature from P300: the passive paradigm requires NO button
press, NO counting, and NO patient cooperation — making it uniquely suited for
assessment in:
  - Unresponsive / comatose patients (ICU CEEG)
  - Non-convulsive status epilepticus (NCSE) monitoring
  - Post-ictal recovery assessment
  - Neonatal and pediatric patients
  - Patients with severe cognitive or motor impairment

Paradigm: Passive 2-tone auditory oddball
  - Standard tones (80%)  — 1 kHz (frequent)
  - Deviant tones  (20%)  — 1.5 kHz (infrequent; no response required)
  Patient is instructed to ignore sounds or watch a silent movie.

Key parameters:
  - MMN latency at Fz: normal ≤200 ms (peak of the mismatch negativity)
  - MMN amplitude at Fz: normal ≥1.5 µV absolute (stored as positive; more = better)
  - P3a latency at Fz: normal ≤280 ms (involuntary attention switch)
  - P3a amplitude at Fz: normal ≥0.8 µV absolute (co-elicited with MMN)
  - MMN asymmetry index: |L_amp − R_amp| / avg_amp × 100
    >30% = abnormal lateralization (temporal lobe pathology)

Diagnostic patterns:
  - Normal: all parameters within reference ranges
  - Delayed MMN: MMN latency >200 ms — slowed pre-attentive auditory processing
  - Absent MMN: no detectable MMN deflection — severe auditory memory deficit /
    consciousness impairment
  - Reduced Amplitude: MMN amplitude <1.5 µV — reduced sensory memory trace strength
  - Lateralized: asymmetry index >30% — suggests temporal lobe pathology ipsilateral
    to larger MMN amplitude (mesial temporal generators)
  - Combined: delayed latency + reduced amplitude — significant pre-attentive deficit

Severity levels: Normal, Mild, Moderate, Severe

References:
  Näätänen R, Paavilainen P, Rinne T, Alho K. The mismatch negativity (MMN)
  in basic research of central auditory processing. Clin Neurophysiol.
  2007;118(12):2544-2590.
  Garrido MI, Kilner JM, Stephan KE, Friston KJ. The mismatch negativity:
  A review of underlying mechanisms. Clin Neurophysiol. 2009;120(3):453-463.
  Näätänen R. Attention and brain function (original MMN framework). 1992.
  Kähkönen S et al. Effects of carbamazepine on MMN. Clin Neurophysiol. 2002.
  ACNS Guideline: Clinical utility of evoked potentials.

Author: Research Team
"""

import sqlite3
import hashlib
from pathlib import Path
from collections import Counter

DB_PATH = str(Path(__file__).parent.parent / "data" / "clinical.db")

# ── Reference ranges ──────────────────────────────────────────────────
MMN_LATENCY_UPPER_MS    = 200.0   # ms — Fz (abnormal if exceeded)
MMN_AMPLITUDE_LOWER_UV  = 1.5    # µV absolute (abnormal if below this)
P3A_LATENCY_UPPER_MS    = 280.0   # ms — Fz involuntary attention switch
P3A_AMPLITUDE_LOWER_UV  = 0.8    # µV absolute
ASYMMETRY_INDEX_UPPER   = 30.0   # % (>30% = abnormal lateralization)

DIAGNOSTIC_PATTERNS = {
    "normal":           "Normal — all parameters within reference ranges",
    "delayed_mmn":      "Delayed MMN — MMN latency >200 ms; slowed pre-attentive auditory processing",
    "absent_mmn":       "Absent MMN — no detectable MMN deflection; severe auditory memory deficit or consciousness impairment",
    "reduced_amplitude":"Reduced Amplitude — MMN amplitude <1.5 µV; reduced sensory memory trace strength",
    "lateralized":      "Lateralized — MMN asymmetry index >30%; suggests temporal lobe pathology ipsilateral to larger amplitude",
    "combined":         "Combined — delayed latency and reduced amplitude; significant pre-attentive deficit",
}

SEVERITY_LEVELS = ["Normal", "Mild", "Moderate", "Severe"]


def _seed(patient_id, comp):
    """Deterministic pseudo-random from patient_id + component."""
    h = hashlib.md5(f"{patient_id}:{comp}".encode()).hexdigest()
    return int(h[:8], 16) / 0xFFFFFFFF


def _get_patients():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()
    cur.execute("""
        SELECT p.patient_id, p.name, p.age, p.disease,
               COUNT(DISTINCT s.id) as seizure_count,
               COUNT(DISTINCT m.id) as med_count,
               AVG(CASE WHEN a.instrument = 'MMSE' THEN a.score END) as mmse_score,
               AVG(CASE WHEN a.instrument = 'MoCA' THEN a.score END) as moca_score
        FROM patients p
        LEFT JOIN seizure_diary s ON p.patient_id = s.patient_id
        LEFT JOIN medications m ON p.patient_id = m.patient_id
        LEFT JOIN assessments a ON p.patient_id = a.patient_id
        GROUP BY p.patient_id
        ORDER BY p.patient_id
        LIMIT 30
    """)
    rows = [dict(r) for r in cur.fetchall()]
    conn.close()
    return rows


def _generate_mmn(patient):
    pid = patient["patient_id"]
    age = patient.get("age", 40) or 40
    disease = (patient.get("disease") or "").lower()
    med_count = patient.get("med_count", 0) or 0
    seizure_count = patient.get("seizure_count", 0) or 0
    mmse = patient.get("mmse_score")
    moca = patient.get("moca_score")

    # Base abnormality probability driven by patient profile
    base_abn = 0.12
    if age > 65:
        base_abn += 0.20
    elif age > 50:
        base_abn += 0.10
    if "epilepsy" in disease:
        base_abn += 0.18   # temporal lobe generators affected
    if "alzheimer" in disease or "dementia" in disease:
        base_abn += 0.35
    if "encephalopathy" in disease or "encephalitis" in disease:
        base_abn += 0.40
    if "depression" in disease:
        base_abn += 0.12
    if "schizophrenia" in disease:
        base_abn += 0.25   # schizophrenia reliably reduces MMN amplitude
    if med_count > 2:
        base_abn += 0.08   # polypharmacy, includes BZD risk
    if seizure_count > 5:
        base_abn += 0.10
    if mmse is not None and mmse < 24:
        base_abn += 0.15
    if moca is not None and moca < 24:
        base_abn += 0.12

    # Lateralization tendency — epilepsy patients more likely to show asymmetry
    lat_tendency = 0.10
    if "epilepsy" in disease:
        lat_tendency += 0.30
    if "temporal" in disease:
        lat_tendency += 0.20

    main_seed  = _seed(pid, "mmn_main")
    sev_seed   = _seed(pid, "mmn_sev")
    pat_seed   = _seed(pid, "mmn_pat")
    hemi_seed  = _seed(pid, "mmn_hemi")
    asym_seed  = _seed(pid, "mmn_asym")
    lat_seed   = _seed(pid, "mmn_lat_side")
    # Separate seed to choose abnormality dimension (latency-only vs amplitude-only vs both)
    dim_seed   = _seed(pid, "mmn_dim")

    is_abnormal = main_seed < min(base_abn, 0.85)

    # ── Generate component values ──────────────────────────────────────
    if not is_abnormal:
        severity    = "Normal"
        mmn_lat     = round(MMN_LATENCY_UPPER_MS * (0.60 + main_seed * 0.30), 1)
        mmn_amp     = round(MMN_AMPLITUDE_LOWER_UV * (1.5 + main_seed * 2.5), 2)
        p3a_lat     = round(P3A_LATENCY_UPPER_MS  * (0.65 + main_seed * 0.25), 1)
        p3a_amp     = round(P3A_AMPLITUDE_LOWER_UV * (1.8 + main_seed * 2.2), 2)
        pattern     = "normal"
    else:
        # dim_seed chooses which dimension(s) are abnormal:
        #   <0.30 → latency-only abnormal (delayed_mmn)
        #   0.30-0.60 → amplitude-only abnormal (reduced_amplitude / lateralized)
        #   >=0.60 → both abnormal (combined / absent / severe)
        lat_only = dim_seed < 0.30
        amp_only = 0.30 <= dim_seed < 0.60

        if sev_seed < 0.35:
            severity = "Mild"
            if lat_only:
                # Latency above reference; amplitude kept normal
                mmn_lat = round(MMN_LATENCY_UPPER_MS * (1.06 + main_seed * 0.12), 1)
                mmn_amp = round(MMN_AMPLITUDE_LOWER_UV * (1.8 + main_seed * 1.2), 2)
            elif amp_only:
                # Amplitude below reference; latency kept normal
                mmn_lat = round(MMN_LATENCY_UPPER_MS * (0.80 + main_seed * 0.15), 1)
                mmn_amp = round(MMN_AMPLITUDE_LOWER_UV * (0.55 + main_seed * 0.40), 2)
            else:
                mmn_lat = round(MMN_LATENCY_UPPER_MS * (1.06 + main_seed * 0.10), 1)
                mmn_amp = round(MMN_AMPLITUDE_LOWER_UV * (0.55 + main_seed * 0.40), 2)
            p3a_lat = round(P3A_LATENCY_UPPER_MS  * (1.05 + main_seed * 0.08), 1)
            p3a_amp = round(P3A_AMPLITUDE_LOWER_UV * (0.72 + main_seed * 0.22), 2)
        elif sev_seed < 0.70:
            severity = "Moderate"
            if lat_only:
                mmn_lat = round(MMN_LATENCY_UPPER_MS * (1.25 + main_seed * 0.20), 1)
                mmn_amp = round(MMN_AMPLITUDE_LOWER_UV * (1.6 + main_seed * 1.0), 2)
            elif amp_only:
                mmn_lat = round(MMN_LATENCY_UPPER_MS * (0.75 + main_seed * 0.20), 1)
                mmn_amp = round(MMN_AMPLITUDE_LOWER_UV * (0.25 + main_seed * 0.25), 2)
            else:
                mmn_lat = round(MMN_LATENCY_UPPER_MS * (1.22 + main_seed * 0.22), 1)
                mmn_amp = round(MMN_AMPLITUDE_LOWER_UV * (0.25 + main_seed * 0.25), 2)
            p3a_lat = round(P3A_LATENCY_UPPER_MS  * (1.20 + main_seed * 0.18), 1)
            p3a_amp = round(P3A_AMPLITUDE_LOWER_UV * (0.40 + main_seed * 0.25), 2)
        else:
            severity = "Severe"
            mmn_lat  = round(MMN_LATENCY_UPPER_MS * (1.50 + main_seed * 0.50), 1)
            mmn_amp  = round(max(0.1, MMN_AMPLITUDE_LOWER_UV * (0.10 + main_seed * 0.25)), 2)
            p3a_lat  = round(P3A_LATENCY_UPPER_MS  * (1.45 + main_seed * 0.35), 1)
            p3a_amp  = round(max(0.05, P3A_AMPLITUDE_LOWER_UV * (0.10 + main_seed * 0.25)), 2)
            lat_only = False
            amp_only = False

        lat_abn = mmn_lat > MMN_LATENCY_UPPER_MS
        amp_abn = mmn_amp < MMN_AMPLITUDE_LOWER_UV

        # Absent MMN — severe cases with pat_seed in lower half
        if severity == "Severe" and pat_seed < 0.55:
            pattern = "absent_mmn"
            mmn_amp = 0.0
            p3a_amp = 0.0
        elif amp_only and (1.0 - asym_seed) < (lat_tendency - 0.05) and hemi_seed < 0.88:
            # Lateralized: amplitude deficit + high epilepsy lateralization tendency,
            # excluding patients whose hemi_seed falls in the symmetric range (≥0.88).
            # (1 - asym_seed) maps the high-asym epilepsy patients to the low end,
            # letting lat_tendency (0.35 effective) select the strongly lateralized ones.
            pattern = "lateralized"
        elif lat_abn and amp_abn:
            pattern = "combined"
        elif lat_abn:
            pattern = "delayed_mmn"
        else:
            pattern = "reduced_amplitude"

    # ── Hemisphere / lateralization data ──────────────────────────────
    # Determine which hemisphere dominates and the asymmetry index
    if pattern == "lateralized":
        # Significant hemispheric asymmetry — one side notably larger
        asymmetry_pct = round(ASYMMETRY_INDEX_UPPER + asym_seed * 40.0, 1)   # 30–70%
        dominant_side = "left" if lat_seed < 0.5 else "right"
        # Distribute amplitude between hemispheres based on asymmetry
        ratio = asymmetry_pct / 100.0
        if mmn_amp > 0:
            smaller_amp = round(mmn_amp * (1.0 - ratio / 2.0), 2)
            larger_amp  = round(mmn_amp * (1.0 + ratio / 2.0), 2)
        else:
            smaller_amp, larger_amp = 0.0, 0.0
        hemisphere_dominant = dominant_side
        if dominant_side == "left":
            mmn_amp_left  = larger_amp
            mmn_amp_right = smaller_amp
        else:
            mmn_amp_left  = smaller_amp
            mmn_amp_right = larger_amp
    elif pattern == "absent_mmn":
        asymmetry_pct       = 0.0
        hemisphere_dominant = "symmetric"
        mmn_amp_left        = 0.0
        mmn_amp_right       = 0.0
    else:
        # Normal or non-lateralized abnormal: mild natural asymmetry
        asymmetry_pct = round(asym_seed * ASYMMETRY_INDEX_UPPER * 0.90, 1)   # <27%
        if hemi_seed < 0.40:
            hemisphere_dominant = "left"
        elif hemi_seed < 0.80:
            hemisphere_dominant = "right"
        else:
            hemisphere_dominant = "symmetric"
        # Small natural inter-hemispheric variation
        ratio = asymmetry_pct / 100.0
        if mmn_amp > 0:
            smaller_amp = round(mmn_amp * (1.0 - ratio / 2.0), 2)
            larger_amp  = round(mmn_amp * (1.0 + ratio / 2.0), 2)
        else:
            smaller_amp, larger_amp = 0.0, 0.0
        if hemisphere_dominant == "left":
            mmn_amp_left  = larger_amp
            mmn_amp_right = smaller_amp
        elif hemisphere_dominant == "right":
            mmn_amp_left  = smaller_amp
            mmn_amp_right = larger_amp
        else:
            mmn_amp_left  = mmn_amp
            mmn_amp_right = mmn_amp

    # ── Abnormality flags ──────────────────────────────────────────────
    mmn_lat_abnormal   = mmn_lat > MMN_LATENCY_UPPER_MS
    mmn_amp_abnormal   = mmn_amp < MMN_AMPLITUDE_LOWER_UV
    p3a_lat_abnormal   = p3a_lat > P3A_LATENCY_UPPER_MS
    p3a_amp_abnormal   = p3a_amp < P3A_AMPLITUDE_LOWER_UV
    asym_abnormal      = asymmetry_pct > ASYMMETRY_INDEX_UPPER

    return {
        "patient_id":          pid,
        "patient_name":        patient.get("name", pid),
        "age":                 age,
        "disease":             patient.get("disease", "Unknown"),
        "severity":            severity,
        "pattern":             pattern,
        # MMN component
        "mmn_latency_ms":      mmn_lat,
        "mmn_amplitude_uv":    mmn_amp,
        # P3a component
        "p3a_latency_ms":      p3a_lat,
        "p3a_amplitude_uv":    p3a_amp,
        # Hemisphere analysis
        "mmn_amp_left_uv":     mmn_amp_left,
        "mmn_amp_right_uv":    mmn_amp_right,
        "asymmetry_index_pct": asymmetry_pct,
        "hemisphere_dominant": hemisphere_dominant,
        # Reference values
        "mmn_ref_upper_ms":    MMN_LATENCY_UPPER_MS,
        "mmn_amp_ref_lower_uv": MMN_AMPLITUDE_LOWER_UV,
        "p3a_ref_upper_ms":    P3A_LATENCY_UPPER_MS,
        "p3a_amp_ref_lower_uv": P3A_AMPLITUDE_LOWER_UV,
        "asym_ref_upper_pct":  ASYMMETRY_INDEX_UPPER,
        # Abnormality flags
        "mmn_lat_abnormal":    mmn_lat_abnormal,
        "mmn_amp_abnormal":    mmn_amp_abnormal,
        "p3a_lat_abnormal":    p3a_lat_abnormal,
        "p3a_amp_abnormal":    p3a_amp_abnormal,
        "asym_abnormal":       asym_abnormal,
        # Clinical context
        "mmse_score":          mmse,
        "moca_score":          moca,
        "med_count":           med_count,
        "seizure_count":       seizure_count,
    }


def _get_all_studies():
    patients = _get_patients()
    return [_generate_mmn(p) for p in patients]


# ── Public API ──────────────────────────────────────────────────────────

def overview():
    """KPIs, severity distribution, diagnostic pattern distribution,
    hemisphere lateralization analysis, AED impact summary, per-patient table."""
    studies = _get_all_studies()
    total = len(studies)

    sev_dist      = Counter(s["severity"] for s in studies)
    pat_dist      = Counter(s["pattern"]  for s in studies)
    abnormal_count = sum(1 for s in studies if s["severity"] != "Normal")

    mean_mmn_lat  = round(sum(s["mmn_latency_ms"]   for s in studies) / total, 1) if total else 0
    mean_mmn_amp  = round(sum(s["mmn_amplitude_uv"] for s in studies) / total, 2) if total else 0
    mean_asym     = round(sum(s["asymmetry_index_pct"] for s in studies) / total, 1) if total else 0

    # Hemisphere / lateralization analysis
    hemi_groups = {
        "left_dominant":  [s for s in studies if s["hemisphere_dominant"] == "left"],
        "right_dominant": [s for s in studies if s["hemisphere_dominant"] == "right"],
        "symmetric":      [s for s in studies if s["hemisphere_dominant"] == "symmetric"],
    }

    def _grp_stats(grp):
        if not grp:
            return {"n": 0, "avg_asymmetry_pct": 0.0, "avg_mmn_amp_uv": 0.0, "abnormal_pct": 0.0}
        return {
            "n": len(grp),
            "avg_asymmetry_pct": round(sum(g["asymmetry_index_pct"] for g in grp) / len(grp), 1),
            "avg_mmn_amp_uv":    round(sum(g["mmn_amplitude_uv"]    for g in grp) / len(grp), 2),
            "abnormal_pct":      round(100 * sum(1 for g in grp if g["severity"] != "Normal") / len(grp), 1),
        }

    hemisphere_analysis = {
        "left_dominant":  _grp_stats(hemi_groups["left_dominant"]),
        "right_dominant": _grp_stats(hemi_groups["right_dominant"]),
        "symmetric":      _grp_stats(hemi_groups["symmetric"]),
    }

    # AED impact (high medication burden >2 meds vs ≤2)
    # MMN is selectively sensitive to benzodiazepines; CBZ/PHT minimally affect it
    high_med = [s for s in studies if s["med_count"] > 2]
    low_med  = [s for s in studies if s["med_count"] <= 2]
    aed_impact = {
        "high_aed_burden": {
            "n":              len(high_med),
            "mean_mmn_amp_uv": round(sum(s["mmn_amplitude_uv"] for s in high_med) / len(high_med), 2) if high_med else 0,
            "abnormal_pct":   round(100 * sum(1 for s in high_med if s["severity"] != "Normal") / len(high_med), 1) if high_med else 0,
        },
        "low_aed_burden": {
            "n":              len(low_med),
            "mean_mmn_amp_uv": round(sum(s["mmn_amplitude_uv"] for s in low_med) / len(low_med), 2) if low_med else 0,
            "abnormal_pct":   round(100 * sum(1 for s in low_med if s["severity"] != "Normal") / len(low_med), 1) if low_med else 0,
        },
    }

    patient_summary = sorted([
        {
            "patient_id":        s["patient_id"],
            "name":              s["patient_name"],
            "age":               s["age"],
            "disease":           s["disease"],
            "severity":          s["severity"],
            "pattern":           s["pattern"],
            "mmn_latency_ms":    s["mmn_latency_ms"],
            "mmn_amplitude_uv":  s["mmn_amplitude_uv"],
            "asymmetry_pct":     s["asymmetry_index_pct"],
            "hemisphere":        s["hemisphere_dominant"],
        }
        for s in studies
    ], key=lambda x: SEVERITY_LEVELS.index(x["severity"]) if x["severity"] in SEVERITY_LEVELS else 0, reverse=True)

    return {
        "kpis": {
            "total_studies":          total,
            "abnormal_count":         abnormal_count,
            "abnormal_rate_pct":      round(100 * abnormal_count / total, 1) if total else 0,
            "mean_mmn_latency_ms":    mean_mmn_lat,
            "mean_mmn_amplitude_uv":  mean_mmn_amp,
            "mean_asymmetry_pct":     mean_asym,
        },
        "severity_distribution": [
            {"severity": sev, "count": sev_dist.get(sev, 0)}
            for sev in SEVERITY_LEVELS
        ],
        "pattern_distribution": [
            {
                "pattern": p,
                "label":   DIAGNOSTIC_PATTERNS[p].split(" — ")[0],
                "count":   pat_dist.get(p, 0),
            }
            for p in ["normal", "delayed_mmn", "absent_mmn", "reduced_amplitude", "lateralized", "combined"]
        ],
        "hemisphere_analysis":    hemisphere_analysis,
        "aed_impact":             aed_impact,
        "patient_summary":        patient_summary,
    }


def breakdown():
    """MMN latency histogram, MMN amplitude histogram, asymmetry distribution,
    component summary (MMN + P3a), per-patient full detail."""
    studies = _get_all_studies()

    # MMN latency histogram (ms)
    lat_buckets = [
        {"range": "<100",    "lo":    0.0, "hi":  100.01},
        {"range": "100-150", "lo":  100.01, "hi":  150.01},
        {"range": "150-200", "lo":  150.01, "hi":  200.01},
        {"range": "200-250", "lo":  200.01, "hi":  250.01},
        {"range": "250+",    "lo":  250.01, "hi": 9999.0},
    ]
    mmn_latency_histogram = [
        {
            "range": b["range"],
            "count": sum(1 for s in studies if b["lo"] <= s["mmn_latency_ms"] < b["hi"]),
        }
        for b in lat_buckets
    ]

    # MMN amplitude histogram (µV absolute)
    amp_buckets = [
        {"range": "<1.0",  "lo": 0.0,  "hi":  1.001},
        {"range": "1.0-1.5","lo": 1.001,"hi":  1.501},
        {"range": "1.5-2.5","lo": 1.501,"hi":  2.501},
        {"range": "2.5-4.0","lo": 2.501,"hi":  4.001},
        {"range": "4.0+",  "lo": 4.001,"hi": 9999.0},
    ]
    mmn_amplitude_histogram = [
        {
            "range": b["range"],
            "count": sum(1 for s in studies if b["lo"] <= s["mmn_amplitude_uv"] < b["hi"]),
        }
        for b in amp_buckets
    ]

    # Asymmetry index distribution (%)
    asym_buckets = [
        {"range": "<10%",  "lo":  0.0, "hi":  10.01},
        {"range": "10-20%","lo": 10.01, "hi":  20.01},
        {"range": "20-30%","lo": 20.01, "hi":  30.01},
        {"range": "30-50%","lo": 30.01, "hi":  50.01},
        {"range": "50%+",  "lo": 50.01, "hi": 9999.0},
    ]
    asymmetry_distribution = [
        {
            "range": b["range"],
            "count": sum(1 for s in studies if b["lo"] <= s["asymmetry_index_pct"] < b["hi"]),
        }
        for b in asym_buckets
    ]

    # Component-level summary
    def _mean(lst):
        return round(sum(lst) / len(lst), 1) if lst else 0

    def _mean2(lst):
        return round(sum(lst) / len(lst), 2) if lst else 0

    component_summary = [
        {
            "component":         "MMN (Fz)",
            "mean_latency_ms":   _mean([s["mmn_latency_ms"]   for s in studies]),
            "ref_upper_ms":      MMN_LATENCY_UPPER_MS,
            "mean_amplitude_uv": _mean2([s["mmn_amplitude_uv"] for s in studies]),
            "ref_lower_uv":      MMN_AMPLITUDE_LOWER_UV,
            "abnormal_pct":      round(
                100 * sum(1 for s in studies if s["mmn_lat_abnormal"] or s["mmn_amp_abnormal"]) / len(studies), 1
            ) if studies else 0,
            "note": "Negative deflection; stored as absolute µV. Passive paradigm — no patient cooperation required.",
        },
        {
            "component":         "P3a (Fz)",
            "mean_latency_ms":   _mean([s["p3a_latency_ms"]   for s in studies]),
            "ref_upper_ms":      P3A_LATENCY_UPPER_MS,
            "mean_amplitude_uv": _mean2([s["p3a_amplitude_uv"] for s in studies]),
            "ref_lower_uv":      P3A_AMPLITUDE_LOWER_UV,
            "abnormal_pct":      round(
                100 * sum(1 for s in studies if s["p3a_lat_abnormal"] or s["p3a_amp_abnormal"]) / len(studies), 1
            ) if studies else 0,
            "note": "Involuntary frontal attention switch; co-elicited with MMN in passive paradigm.",
        },
    ]

    # Per-patient full detail (sorted by severity then MMN latency descending)
    patient_details = sorted([
        {
            "patient_id":          s["patient_id"],
            "name":                s["patient_name"],
            "age":                 s["age"],
            "disease":             s["disease"],
            "severity":            s["severity"],
            "pattern":             s["pattern"],
            "mmn_latency_ms":      s["mmn_latency_ms"],
            "mmn_amplitude_uv":    s["mmn_amplitude_uv"],
            "p3a_latency_ms":      s["p3a_latency_ms"],
            "p3a_amplitude_uv":    s["p3a_amplitude_uv"],
            "mmn_amp_left_uv":     s["mmn_amp_left_uv"],
            "mmn_amp_right_uv":    s["mmn_amp_right_uv"],
            "asymmetry_index_pct": s["asymmetry_index_pct"],
            "hemisphere_dominant": s["hemisphere_dominant"],
            "mmn_lat_abn":         s["mmn_lat_abnormal"],
            "mmn_amp_abn":         s["mmn_amp_abnormal"],
            "p3a_lat_abn":         s["p3a_lat_abnormal"],
            "p3a_amp_abn":         s["p3a_amp_abnormal"],
            "asym_abn":            s["asym_abnormal"],
            "mmse":                s["mmse_score"],
            "moca":                s["moca_score"],
            "med_count":           s["med_count"],
            "seizure_count":       s["seizure_count"],
        }
        for s in studies
    ], key=lambda x: (
        SEVERITY_LEVELS.index(x["severity"]) if x["severity"] in SEVERITY_LEVELS else 0,
        x["mmn_latency_ms"],
    ), reverse=True)

    return {
        "mmn_latency_histogram":   mmn_latency_histogram,
        "mmn_amplitude_histogram": mmn_amplitude_histogram,
        "asymmetry_distribution":  asymmetry_distribution,
        "component_summary":       component_summary,
        "patient_details":         patient_details,
    }


def definitions():
    """MMN protocol, component definitions, reference ranges,
    diagnostic patterns, epilepsy relevance contexts, and clinical references."""
    return {
        "title": "MMN — Mismatch Negativity (Pre-Attentive Auditory ERP)",
        "protocol": {
            "description": (
                "The Mismatch Negativity (MMN) is a negative ERP deflection, maximal at Fz/FCz, "
                "peaking 100–200 ms after an auditory change (deviant stimulus) embedded within a "
                "sequence of repetitive standard sounds. It reflects an automatic, pre-attentive "
                "auditory change detection mechanism generated in the bilateral auditory cortex "
                "(primary and secondary temporal areas) and prefrontal cortex, without requiring "
                "patient attention, task performance, or motor responses. The passive paradigm "
                "makes MMN the only auditory ERP fully obtainable in unresponsive patients."
            ),
            "recording_sites": ["Fz", "FCz", "Cz", "T7", "T8"],
            "paradigm": "Passive 2-tone auditory oddball (standard 1 kHz / deviant 1.5 kHz; no button press)",
            "epoch_window": "-100 to +400 ms relative to deviant stimulus onset",
            "standard": (
                "Näätänen R et al (2007) Clin Neurophysiol 118:2544-2590. "
                "Garrido MI et al (2009) Clin Neurophysiol 120:453-463. "
                "ACNS Guideline: Clinical utility of evoked potentials."
            ),
            "indications": [
                "Consciousness assessment in unresponsive / comatose patients",
                "Non-convulsive status epilepticus (NCSE) monitoring — ICU CEEG",
                "Post-ictal recovery assessment (recovers faster than P300)",
                "Auditory cortex maturation — neonatal and pediatric epilepsy syndromes",
                "TLE presurgical lateralization (temporal lobe asymmetry)",
                "AED auditory neurotoxicity monitoring (benzodiazepines, barbiturates)",
                "Schizophrenia / psychiatric comorbidity (MMN reliably reduced in SZ)",
                "Encephalopathy grading — sensory memory integrity in ICU patients",
            ],
        },
        "parameters": [
            {
                "name": "MMN Latency (Fz)",
                "unit": "ms",
                "description": (
                    "Peak latency of the mismatch negativity at Fz, measured as the time from "
                    "the onset of the deviant stimulus to the peak negative deflection. Reflects "
                    "the speed of automatic auditory change detection (pre-attentive memory "
                    "comparison). Prolonged MMN latency indicates slowed sensory memory processing "
                    "and is seen in encephalopathy, deep post-ictal states, and severe AED toxicity "
                    "(barbiturates, benzodiazepines). Unlike P300, MMN latency is not strongly "
                    "age-dependent. Reference: ≤200 ms."
                ),
            },
            {
                "name": "MMN Amplitude (Fz)",
                "unit": "µV (absolute, representing a negative deflection)",
                "description": (
                    "Peak amplitude of the MMN at Fz, stored as an absolute (positive) value "
                    "representing the magnitude of the negative deflection from baseline. A larger "
                    "(more negative) amplitude reflects a stronger pre-attentive auditory memory "
                    "trace. Reduced MMN amplitude is the most reliable biomarker in schizophrenia "
                    "(meta-analysis N>2,000), and is also reduced in temporal lobe epilepsy, "
                    "post-GTCS states, and benzodiazepine administration. "
                    "Reference: ≥1.5 µV (|−1.5 µV| or greater)."
                ),
            },
            {
                "name": "P3a Latency (Fz)",
                "unit": "ms",
                "description": (
                    "Latency of the P3a (novelty P300) component, a frontal positive deflection "
                    "co-elicited with the MMN in the passive paradigm. It reflects an involuntary "
                    "attention switch triggered by the deviant sound, independent of conscious "
                    "task engagement. Distinct from the P3b (requires attention), the P3a can "
                    "be elicited in passive or impaired-consciousness states. Prolonged P3a "
                    "latency suggests impaired automatic attentional reorienting. "
                    "Reference: ≤280 ms."
                ),
            },
            {
                "name": "MMN Asymmetry Index (T7/T8)",
                "unit": "% inter-hemispheric difference",
                "description": (
                    "Percentage difference between left (T7) and right (T8) temporal MMN "
                    "amplitudes: |L_amp − R_amp| / avg_amp × 100. Normally <30%. "
                    "An asymmetry index >30% reflects lateralized auditory cortex dysfunction, "
                    "clinically significant for identifying the seizure focus hemisphere in "
                    "temporal lobe epilepsy. Larger MMN amplitude is ipsilateral to the "
                    "epileptic focus (mesial temporal generators; Näätänen 2007). "
                    "Critical for non-invasive presurgical lateralization."
                ),
            },
        ],
        "reference_ranges": {
            "mmn_latency_upper_ms":     MMN_LATENCY_UPPER_MS,
            "mmn_amplitude_lower_uv":   MMN_AMPLITUDE_LOWER_UV,
            "p3a_latency_upper_ms":     P3A_LATENCY_UPPER_MS,
            "p3a_amplitude_lower_uv":   P3A_AMPLITUDE_LOWER_UV,
            "asymmetry_index_upper_pct": ASYMMETRY_INDEX_UPPER,
            "notes": (
                "MMN latency and amplitude references are adult normative values. Unlike P300, "
                "MMN latency is NOT strongly age-adjusted — minimal age effect (Näätänen 2007). "
                "Amplitude varies with deviant magnitude (frequency difference: 1 kHz vs 1.5 kHz "
                "is a 50% frequency change — high-contrast paradigm ensuring reliable MMN). "
                "Asymmetry reference: AANEM consensus and Näätänen 2007 temporal lateralization data."
            ),
        },
        "diagnostic_patterns": [
            {"pattern": k, "description": v}
            for k, v in DIAGNOSTIC_PATTERNS.items()
        ],
        "severity_levels": [
            {
                "level": "Normal",
                "criteria": (
                    "MMN latency ≤200 ms; MMN amplitude ≥1.5 µV; P3a latency ≤280 ms; "
                    "asymmetry index ≤30%. Pre-attentive auditory processing intact."
                ),
            },
            {
                "level": "Mild",
                "criteria": (
                    "MMN latency 200–240 ms OR amplitude 1.0–1.5 µV OR asymmetry 30–45%. "
                    "Minor pre-attentive processing slowing or mild lateralized deficit."
                ),
            },
            {
                "level": "Moderate",
                "criteria": (
                    "MMN latency 240–300 ms OR amplitude 0.5–1.0 µV OR asymmetry 45–60%. "
                    "Significant sensory memory impairment or moderate hemispheric asymmetry."
                ),
            },
            {
                "level": "Severe",
                "criteria": (
                    "MMN latency >300 ms OR amplitude <0.5 µV OR absent MMN OR asymmetry >60%. "
                    "Severe pre-attentive auditory failure; consider NCSE, encephalopathy, "
                    "or bilateral auditory cortex dysfunction."
                ),
            },
        ],
        "epilepsy_relevance": [
            {
                "context": "NCSE / Consciousness Monitoring",
                "detail": (
                    "Preserved MMN in comatose or unresponsive patients confirms intact auditory "
                    "sensory memory without requiring cooperation — uniquely valuable in ICU "
                    "continuous EEG (CEEG) settings. Absent MMN in the context of diffuse "
                    "slowing supports metabolic encephalopathy or NCSE with impaired cortical "
                    "processing. Unlike P300 or SSEP, MMN can be continuously recorded passively "
                    "during routine CEEG without interrupting monitoring."
                ),
            },
            {
                "context": "Post-Ictal Recovery Assessment",
                "detail": (
                    "MMN recovers significantly faster than P300 after generalized tonic-clonic "
                    "seizures (GTCS): MMN typically normalizes within 15–30 minutes post-ictally, "
                    "while P300 may remain prolonged for 30–120 minutes. Serial MMN recording "
                    "provides an earlier objective marker of post-ictal cortical recovery, "
                    "complementing clinical assessment and potentially guiding return-to-activity "
                    "decisions in sports-related seizures and post-operative epilepsy monitoring."
                ),
            },
            {
                "context": "TLE Lateralization and Presurgical Evaluation",
                "detail": (
                    "In temporal lobe epilepsy (TLE), the hemisphere ipsilateral to the seizure "
                    "focus generates a paradoxically larger MMN amplitude (T7/T8 asymmetry), "
                    "reflecting increased excitability of the mesial temporal auditory memory "
                    "circuit (Näätänen 2007). An MMN asymmetry index >30% with right lateralization "
                    "supports right TLE. This non-invasive lateralization complements "
                    "neuropsychological testing, fMRI language mapping, and Wada testing in "
                    "presurgical planning, reducing the need for invasive intracranial EEG."
                ),
            },
            {
                "context": "AED Auditory Effects Monitoring",
                "detail": (
                    "Benzodiazepines (lorazepam, clonazepam, diazepam) acutely reduce MMN "
                    "amplitude — an important confound in ICU CEEG patients on BZD rescue therapy "
                    "(Kähkönen 2002). Phenytoin and carbamazepine have minimal MMN impact (unlike "
                    "their significant P300 effects), making MMN more robust than P300 for "
                    "monitoring patients on sodium channel blockers. Valproate and levetiracetam "
                    "do not significantly affect MMN, preserving its utility as a chronic monitoring "
                    "tool in common AED regimens."
                ),
            },
            {
                "context": "Neonatal and Pediatric Epilepsy Syndromes",
                "detail": (
                    "MMN is detectable from birth (even in preterm neonates at 30 weeks gestational "
                    "age), making it the only cognitive ERP fully applicable to neonatal and "
                    "pediatric populations without requiring behavioral compliance. In infantile "
                    "spasms (West syndrome) and Lennox-Gastaut syndrome (LGS), serial MMN tracking "
                    "monitors auditory cortex maturation and the impact of epilepsy and AED "
                    "treatment on developing cortical pre-attentive processing — a functional "
                    "outcome measure independent of developmental stage or motor ability."
                ),
            },
        ],
        "reference": (
            "Näätänen R, Paavilainen P, Rinne T, Alho K. The mismatch negativity (MMN) in basic "
            "research of central auditory processing. Clin Neurophysiol. 2007;118(12):2544-2590. "
            "Garrido MI, Kilner JM, Stephan KE, Friston KJ. The mismatch negativity: A review of "
            "underlying mechanisms. Clin Neurophysiol. 2009;120(3):453-463. "
            "Näätänen R. Attention and brain function. Erlbaum, Hillsdale NJ. 1992 (original MMN framework). "
            "Kähkönen S, Ahveninen J, Jääskeläinen IP, Kaakkola S, Naatanen R, Huttunen J. "
            "Effects of haloperidol on selective attention: a combined whole-head MEG and high-resolution "
            "EEG study. Neuropsychopharmacology. 2001. "
            "Kähkönen S et al. Effects of carbamazepine and valproate on mismatch negativity. "
            "Clin Neurophysiol. 2002;113(10):1494-1498. "
            "ACNS Guideline: Clinical utility of evoked potentials."
        ),
    }


if __name__ == "__main__":
    import json
    print("=== MMN Dashboard Overview ===")
    ov = overview()
    print(json.dumps(ov["kpis"], indent=2))
    print(f"Severity: {ov['severity_distribution']}")
    print(f"Patterns: {ov['pattern_distribution']}")
    print(f"Hemisphere analysis: {ov['hemisphere_analysis']}")
    print(f"\n=== Breakdown ===")
    bd = breakdown()
    print(f"MMN latency histogram: {bd['mmn_latency_histogram']}")
    print(f"MMN amplitude histogram: {bd['mmn_amplitude_histogram']}")
    print(f"Asymmetry distribution: {bd['asymmetry_distribution']}")
    print(f"Components: {[c['component'] for c in bd['component_summary']]}")
    print(f"\n=== Definitions ===")
    df = definitions()
    print(f"Parameters: {len(df['parameters'])}")
    print(f"Epilepsy contexts: {len(df['epilepsy_relevance'])}")
    print(f"Diagnostic patterns: {len(df['diagnostic_patterns'])}")
