#!/usr/bin/env python3
"""Generate STATUS.md — a single Done/Pending view of the whole platform, from REAL sources:
config registries (built/partial/planned), cron jobs, recent commits, and live API health.
§62 checklist format. Run: python3 scripts/status_report.py  (or via STATUS-REPORT cron)."""
import json, subprocess, sys, glob
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def sh(cmd):
    try:
        return subprocess.run(cmd, shell=True, cwd=ROOT, capture_output=True, text=True, timeout=30).stdout.strip()
    except Exception:
        return ""


def load(p):
    try:
        return json.loads((ROOT / p).read_text())
    except Exception:
        return {}


def count_status(items, key="status"):
    from collections import Counter
    c = Counter((i.get(key) or "?") for i in items)
    return dict(c)


def main():
    now_local = datetime.now(timezone.utc).astimezone().strftime("%Y-%m-%d %H:%M %Z")
    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    # registries with built/partial/planned status
    registries = {
        "Clinical Data Manager tasks": load("config/data_manager.json").get("tasks", []),
        "Expert dashboards": load("config/expert_dashboards.json").get("dashboards", []),
        "Neuro AI ecosystem tools": [t for c in load("config/neuro_ai_ecosystem.json").get("categories", []) for t in c.get("tools", [])],
        "EEG AI stack tools": [t for L in load("config/eeg_ai_stack.json").get("layers", []) for t in L.get("tools", [])],
    }

    # cron jobs
    crons = [l for l in sh("crontab -l").splitlines() if l.strip() and not l.strip().startswith("#") and "agenticfinder" in l]
    jobs_cfg = load("config/jobs.json").get("jobs", [])

    # recent commits (completed work)
    commits = sh("git log --oneline -15 --no-decorate").splitlines()
    ahead = sh("git rev-list --count origin/main..HEAD 2>/dev/null") or "?"

    # api health
    eps = ["fairness", "shap-explain", "clinical-trust", "drift", "data-manager", "eeg-viz/presets",
           "expert-dashboards", "neuro-ai-ecosystem", "jobs"]
    health = {}
    for e in eps:
        code = sh(f"curl -s -o /dev/null -w '%{{http_code}}' http://127.0.0.1:8010/api/{e} -m 10")
        health[e] = code or "down"

    # build markdown
    out = [f"# 📊 Project STATUS — agenticfinder\n",
           f"> Auto-generated by `scripts/status_report.py` · {now_local} ({now_utc})  ",
           f"> Regenerate: `python3 scripts/status_report.py` · refreshed daily by STATUS-REPORT cron\n",
           "---\n", "## ✅ Done (completed & verified)\n"]

    # done = built items + recent commits + working endpoints
    for name, items in registries.items():
        cs = count_status(items)
        built = cs.get("built", 0) + cs.get("installed", 0)
        out.append(f"- [x] **{name}**: {built} built/installed of {len(items)} "
                   f"({', '.join(f'{k}:{v}' for k,v in sorted(cs.items()))})")
    out.append(f"- [x] **Cron jobs running**: {len(jobs_cfg)} registered")
    up = sum(1 for v in health.values() if v == "200")
    out.append(f"- [x] **API endpoints live**: {up}/{len(health)} returning 200")
    out.append("\n**Recent completed commits:**")
    for c in commits[:12]:
        out.append(f"- [x] `{c[:7]}` {c[8:115]}")

    out.append("\n---\n## ⏳ Pending (planned / partial / not done)\n")
    for name, items in registries.items():
        cs = count_status(items)
        pend = cs.get("planned", 0) + cs.get("partial", 0) + cs.get("cataloged", 0)
        if pend:
            planned = [i.get("name", "?") for i in items if i.get("status") in ("planned", "cataloged")][:8]
            out.append(f"- [ ] **{name}**: {pend} not-yet-built — {', '.join(planned[:6])}{' …' if len(planned)>6 else ''}")
    out.append(f"\n**Unpushed commits (gated §42):** {ahead} — push needs operator go-ahead")
    out.append("\n**Top buildable next (no blockers):**")
    out.append("- [ ] Retrain on same-setup ictal/interictal (removes dataset confound)")
    out.append("- [ ] Spike/sharp-wave overlay · Seizure timeline (CHB-MIT annotations)")
    out.append("- [ ] Patient Comparison UI · remaining cognitive tests + assessments")
    out.append("- [ ] Next expert modules (Pharmacist, Epilepsy Nurse, SLP, OT, Dietitian, …)")
    out.append("\n**Blocked (need operator input):** Gmail/Slack/Drive live (credentials) · multi-user auth · EMR/FHIR\n")

    md = "\n".join(out) + "\n"
    (ROOT / "STATUS.md").write_text(md)
    # also drop a json snapshot for machine reads
    (ROOT / "jobs" / "reports").mkdir(parents=True, exist_ok=True)
    (ROOT / "jobs" / "reports" / "status_latest.json").write_text(json.dumps(
        {"generated": now_utc, "registries": {k: count_status(v) for k, v in registries.items()},
         "endpoints": health, "commits_ahead": ahead, "jobs": len(jobs_cfg)}, indent=2))
    print(f"STATUS.md written ({now_local}) — {up}/{len(health)} endpoints up, {ahead} commits ahead")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
