"""
WDR45 BPAN (Beta-propeller protein-associated neurodegeneration) — NBIA5
=========================================================================
40-patient cohort · WDR45 (Xp11.23) · X-linked Dominant · De Novo in Females
Biphasic: Childhood static encephalopathy → Late-onset parkinsonism + dementia
MRI T2*/SWI: Substantia nigra + globus pallidus iron PATHOGNOMONIC (NBIA)
No precision therapy 2026 · Deferiprone trials ongoing (NBIA Research Institute)

WDR45 BIOLOGY:
WDR45 (WD repeat domain 45, also known as WIPI4 — WD repeat domain, phosphoinositide-
interacting protein 4) encodes a 309-amino-acid protein belonging to the PROPPIN family
(beta-propeller proteins that bind phosphoinositides).

WDR45 PROTEIN STRUCTURE (309 aa, Xp11.23):
  BETA-PROPELLER CORE (aa 1–309): 7-bladed beta-propeller. Each blade consists of
    4 antiparallel beta-strands (A, B, C, D). Blades 1–7 form a torus-like structure
    creating a central channel.
  FYVE-RELATED PI3P BINDING SITE (blades 5–7): Contains the canonical WFDE motif
    (Trp–Phe–Asp–Glu) that recognises phosphatidylinositol 3-phosphate (PI3P).
    PI3P binding is essential for autophagosome membrane recruitment.
    WDR45 localises to the phagophore via PI3P — like WIPI1/2/3/4 family members.
  PROTEIN INTERACTION SURFACES:
    - ATG2A/ATG2B binding (blades 2–4): WDR45 recruits ATG2A/B to the phagophore edge
      for lipid transfer (ER → forming phagophore membrane elongation).
    - ULK1/2 interaction (blade 1 N-terminal loop): WDR45 bridges ULK1 autophagy
      initiation complex to the elongation machinery.
    - GABARAPL1/LC3 interaction (blade 6 loop): LIR-like motif permits WDR45-autophagosome
      cargo association during membrane closure.
  KEY MISSENSE PATHOGENIC VARIANTS:
    p.Arg152Trp (blade 4–5 interface): disrupts PI3P-binding groove; most common missense.
    p.Thr200Ile (blade 5 B-strand): reduces ATG2A co-recruitment by 70%.
    p.Asp235Asn (WFDE → WNFE): eliminates PI3P binding; severe phenotype.
    p.Leu261Pro (blade 6): disrupts blade stability; partial loss of function; attenuated.

WDR45 FUNCTION — AUTOPHAGY:
WDR45 is an essential scaffold at the interface of autophagy initiation (ULK1 complex)
and phagophore elongation (ATG2A/B lipid transfer). In the absence of functional WDR45:
  1. PI3P generated by VPS34/PIK3C3 complex at the ER-phagophore contact site is not
     'read' — phagophore cannot be maintained at the omegasome (ER-derived autophagy
     initiation platform).
  2. ATG2A/B fail to be recruited to phagophore edges → ER-to-phagophore lipid transfer
     is severely impaired → phagophore elongation stalls → autophagosome closure fails.
  3. Consequence: accumulation of incomplete autophagosome intermediates, failure of
     substrate sequestration (organelles + aggregated proteins + iron-ferritin complexes).
  4. Mitophagy failure: dysfunctional mitochondria accumulate → reactive oxygen species
     generation → oxidative stress in neurons (dopaminergic SN neurons most vulnerable).
  5. Ferritinophagy failure: ferritin-iron complexes are normally cleared by the
     selective autophagy receptor NCOA4 (ferritinophagy receptor) → autolysosomes.
     WDR45 LOF → ferritin clearance failure → ferritin deposition → eventual iron
     release (labile iron pool ↑) → ferroptosis in SN and GP neurons → brain iron
     accumulation (T2*/SWI hypointensity — BPAN radiological signature).

BIPHASIC PHENOTYPE:
PHASE 1 — STATIC ENCEPHALOPATHY (Birth to ~10 years):
  - Global developmental delay: moderate-profound intellectual disability (IQ typically
    <40 in profoundly affected; up to ~55 in mildly affected missense variants).
  - Language: absent speech (70%) or severely limited (<10 words lifetime, 20%).
  - Autism spectrum features: 60–70% (social withdrawal, repetitive behaviors,
    sensory sensitivities — similar to Angelman but without happy affect or seizure
    predominance in infancy).
  - Epilepsy onset: median 18 months (range neonatal to 5 years).
    Seizure types:
      Focal seizures (with or without secondary generalisation): 80%
      Absence seizures: 60% (sometimes the presenting seizure type, may mimic CAE)
      Generalised tonic-clonic: 50%
      Myoclonic: 40%
      Infantile spasms / West syndrome: 25% (early-onset group, <12 months)
      Epileptic spasms (non-IS age): 15%
      Atonic/drop attacks: 20% (add-on, associated with Lennox-Gastaut evolution)
  - EEG: generalised slowing, multifocal epileptiform discharges, burst-suppression
    (early-onset group), hypsarrhythmia (IS subgroup), spike-wave complexes.
  - Hypotonia: universal (100%), often the presenting sign in neonatal period.
  - Stereotypies: hand-wringing (35%), not as dominant as Rett.
  - RELATIVELY STABLE — hence "static" encephalopathy of childhood; gains may occur
    with intensive therapy but no acute deterioration until Phase 2.
  - Sleep disturbances: already apparent in childhood (25%); worsened in Phase 2.

PHASE 2 — NEURODEGENERATION (Adolescence to early adulthood, typically 15–30 years):
  - SUDDEN neurodegeneration onset (over weeks to months, not years) — key clinical feature.
  - Rapidly progressive parkinsonism:
      Rigidity (cogwheel and lead-pipe): 100% of Phase 2 patients
      Bradykinesia: 95%
      Resting tremor: 60% (less dominant than idiopathic PD)
      Postural instability: 80%
  - Rapidly progressive dementia:
      Episodic memory loss: 100%
      Executive dysfunction: 95%
      Language deterioration: 80%
      Behavioural changes (impulsivity, aggression): 60%
  - Dystonia: 70% (often limb-onset, generalises rapidly)
  - Spasticity: 50% (upper motor neuron involvement)
  - REM sleep behaviour disorder: 65% (iron in substantia nigra — same mechanism as PD/DLB)
  - Vivid dreams, nightmares: 55%
  - L-DOPA response: partial/transient in 40–50% (Phase 2 onset)
  - Progression: severe disability by 3rd decade; most lose independent ambulation
    within 5 years of Phase 2 onset.

MRI — PATHOGNOMONIC FINDINGS:
  T2*/GRE/SWI:
    - Substantia nigra pars reticulata (SNr): hypointensity PATHOGNOMONIC for BPAN.
      Present in early Phase 2 (may appear even in late Phase 1 on SWI).
    - Globus pallidus interna (GPi): hypointensity. Less dominant than PKAN.
    - "Halo sign" on T1: hyperintense rim around hypointense SN core on T1-weighted images
      (specific for BPAN among NBIA syndromes; reflects iron-mediated T1 shortening).
  Other:
    - Thin corpus callosum (body/splenium): 55%
    - Hippocampal signal changes: 30% (T2 hyperintensity; correlates with dementia)
    - Cerebellar atrophy: 40% (Phase 2)
    - Diffuse cerebral atrophy: 60% (Phase 2)
  NBIA differential by MRI:
    PKAN (PANK2): Eye-of-tiger sign in GP (T2 central hyperintensity + hypointense rim);
      no SN predominance.
    MPAN (C19orf12): SN + GP + striatum iron; optic atrophy; motor neuropathy.
    BPAN (WDR45): SN predominant + GP + "halo sign" T1; childhood epilepsy prominent;
      biphasic course is the key CLINICAL distinguisher.

AED MANAGEMENT:
  PHASE 1 (Epilepsy management):
    FIRST LINE:
      LEV (Levetiracetam): Level B — broad-spectrum; reduces focal and generalised
        seizures; good safety profile; no significant mitochondrial risk.
      VPA (Valproate): Level B — effective for myoclonic + absence + GTCS; HIGH CAUTION —
        POLG mandatory before initiating (VPA contraindicated in mitochondrial disease;
        BPAN is primarily autophagic but mitochondrial dysfunction secondary to WDR45 LOF
        makes POLG testing clinically mandatory per expert consensus 2024).
      CLB (Clobazam): Level B — add-on for focal-onset and Lennox-Gastaut evolution.
    INFANTILE SPASMS (Phase 1, IS subgroup):
      ACTH + VGB (UKISS protocol): Level A — standard IS treatment.
      VGB REMS monitoring (16-week): mandatory (visual fields).
    ADD-ON:
      ZNS (Zonisamide): Level C — for myoclonic predominant.
      TPM (Topiramate): Level C — for focal + drop attacks.
      RFN (Rufinamide): Level C — for Lennox-Gastaut evolution (drop attacks).
      KD (Ketogenic Diet): Level C — for drug-resistant epilepsy in Phase 1.
    AVOID:
      PHT (Phenytoin): AVOID — worsen myoclonus; no evidence; narrow therapeutic window.
      CBZ (Carbamazepine): AVOID — may aggravate myoclonic and absence seizures.
      OXC (Oxcarbazepine): AVOID — similar to CBZ profile.
  PHASE 2 (Parkinsonism management):
    L-DOPA/carbidopa: Level C — trial mandatory; 40–50% partial response; taper if not helpful.
    Amantadine: Level C — may help tremor and dyskinesia.
    Iron chelation (Deferiprone): INVESTIGATIONAL — TIRCON study + NBIA Research Institute
      trials ongoing 2026; mechanism: deferiprone crosses BBB, chelates labile iron pool in
      SN/GP, reduces ferroptosis; early Phase 2 trials show MRI iron reduction but functional
      benefit unclear; do not use outside trial without neurologist oversight.
    CoQ10 + Riboflavin: Level C — mitochondrial support (secondary mitochondrial dysfunction
      in BPAN); theoretical basis only.
    Rapamycin/Sirolimus: INVESTIGATIONAL — mTOR inhibition to enhance residual autophagy flux;
      murine models show partial rescue; human data limited.
  CONTRAINDICATIONS:
    PHT — ABSOLUTE CI (myoclonus aggravation + no evidence for focal seizure control in BPAN).
    CBZ/OXC — AVOID (may worsen myoclonic-absence component; sodium channel blockers may
      increase seizure burden in BPAN children with mixed epilepsy).
    VPA in known POLG mutations — ABSOLUTE CI (fatal hepatotoxicity, Alpers syndrome).
    Vigabatrin (VGB) > 16 weeks continuous without REMS ophthalmology — ABSOLUTE CI.

DIAGNOSIS:
  1. Molecular: WDR45 gene sequencing (trio exome preferred — de novo detection).
     Panel: NBIA gene panel (WDR45, PANK2, C19orf12, PLA2G6, COASY, FA2H, ATP13A2, CP).
  2. MRI (SWI/GRE): T2* hypointensity SN + GP + "halo sign" T1.
     NOTE: Iron may be ABSENT in childhood Phase 1 scans — does NOT exclude BPAN.
     Repeat MRI with SWI in adolescence if clinical suspicion high.
  3. No diagnostic biochemical biomarker (NOT a metabolic disorder — no plasma amino acids,
     organic acids, MMA, homocysteine, lysosomal enzyme panels relevant).
  4. Ophthalmological: Optic pallor (30% late Phase 2) — NOT optic atrophy as prominent
     as MPAN; retinal iron deposits on fundus rare.

KEY CLINICAL PEARLS:
  1. BPAN is clinically INVISIBLE in Phase 1 (looks like non-specific ID + epilepsy).
     The BIPHASIC COURSE is the key diagnostic trigger — suspect BPAN in any female with
     childhood-onset ID + epilepsy who develops parkinsonism or dementia in 2nd–3rd decade.
  2. 90% females (de novo X-linked dominant) — rare in males (hemizygous/mosaic).
     X-chromosome inactivation (XCI) in carrier females: random skewing does NOT reliably
     explain severity (unlike other X-linked conditions); pathogenicity from de novo allele
     on active X drives disease.
  3. MRI SWI is the diagnostic key imaging — request explicitly as it may not be included
     in standard brain MRI protocols; must ask for T2*/GRE/SWI sequence.
  4. POLG testing MANDATORY before VPA in all BPAN patients (secondary mitochondrial
     dysfunction makes mitochondrial toxicity risk clinically relevant).
  5. Iron chelation (deferiprone) is the future precision therapy but remains investigational
     in 2026 — refer to NBIA Research Institute clinical trial network.

PREVALENCE: ~1:1,000,000 total; ~1:500,000 females (de novo X-linked dominant).
Estimated ~3,000–5,000 individuals worldwide with BPAN (highly underdiagnosed pre-SWI MRI era).

OMIM: Gene WDR45 #300526 · Disease BPAN/NBIA5 #300643 · Chromosome Xp11.23
"""

import random
import math

SEED = 515
RNG = random.Random(SEED)

N = 40
# 90% females (X-linked dominant de novo), 10% males (mosaic/hemizygous-hypomorphic)
N_FEMALE = 36
N_MALE = 4

# ── Etiology distribution ──────────────────────────────────────────────────
ETIOLOGIES = [
    {"etiology": "WDR45 Truncating/Frameshift (PTC/fs — Null)",
     "n": 30, "pct": 75,
     "mechanism": "Nonsense or frameshift → premature termination codon → NMD → absent protein → complete autophagy scaffold loss",
     "severity": "Severe (profound ID, absent speech, early IS, Phase 2 onset 15–22yr)"},
    {"etiology": "WDR45 Missense (beta-propeller interface)",
     "n": 6, "pct": 15,
     "mechanism": "Missense in PI3P-binding groove or ATG2-interaction surface → partial autophagy scaffold loss",
     "severity": "Moderate-Severe (moderate-profound ID, some acquire words, Phase 2 onset 22–28yr)"},
    {"etiology": "WDR45 Splice Site (partial exon skip)",
     "n": 3, "pct": 7,
     "mechanism": "Intronic splice variant → partial exon skipping → hypomorphic protein with reduced PI3P binding",
     "severity": "Moderate (moderate ID, attenuated parkinsonism)"},
    {"etiology": "WDR45 Large Deletion/CNV (exonic del Xp11.23)",
     "n": 1, "pct": 3,
     "mechanism": "Multi-exon deletion → complete gene loss → null → contiguous gene involvement possible",
     "severity": "Severe-Profound (depends on deletion boundary)"},
]

# ── Seizure type distribution ──────────────────────────────────────────────
SEIZURE_TYPES = [
    {"type": "Focal (with/without secondary generalisation)", "pct": 80, "n": 32},
    {"type": "Absence", "pct": 60, "n": 24},
    {"type": "Generalised Tonic-Clonic (GTCS)", "pct": 50, "n": 20},
    {"type": "Myoclonic", "pct": 40, "n": 16},
    {"type": "Infantile Spasms (West Syndrome)", "pct": 25, "n": 10},
    {"type": "Atonic/Drop Attacks", "pct": 20, "n": 8},
    {"type": "Epileptic Spasms (non-IS age)", "pct": 15, "n": 6},
    {"type": "Tonic", "pct": 12, "n": 5},
]

# ── AED response data ──────────────────────────────────────────────────────
TREATMENTS = [
    {"drug": "LEV (Levetiracetam)", "level": "B", "tried_pct": 88, "responder_pct": 45,
     "note": "First-line broad-spectrum; no mitochondrial risk; add SB supplementation"},
    {"drug": "VPA (Valproate)", "level": "B", "tried_pct": 70, "responder_pct": 52,
     "note": "POLG MANDATORY BEFORE USE; effective for myoclonic+absence+GTCS; HIGH CAUTION mitochondrial risk"},
    {"drug": "CLB (Clobazam)", "level": "B", "tried_pct": 65, "responder_pct": 48,
     "note": "Add-on for focal-onset, Lennox-Gastaut evolution; tolerance develops"},
    {"drug": "ACTH + VGB (UKISS — IS group)", "level": "A", "tried_pct": 25, "responder_pct": 68,
     "note": "Standard IS protocol for the 25% with infantile spasms; VGB REMS 16-week mandatory"},
    {"drug": "ZNS (Zonisamide)", "level": "C", "tried_pct": 40, "responder_pct": 38,
     "note": "Add-on for myoclonic predominant; carbonic anhydrase inhibition"},
    {"drug": "TPM (Topiramate)", "level": "C", "tried_pct": 35, "responder_pct": 35,
     "note": "Focal + drop attacks; cognitive side effects limit use in ID"},
    {"drug": "RFN (Rufinamide)", "level": "C", "tried_pct": 20, "responder_pct": 40,
     "note": "Lennox-Gastaut atonic drops; good add-on safety"},
    {"drug": "KD (Ketogenic Diet)", "level": "C", "tried_pct": 45, "responder_pct": 42,
     "note": "Drug-resistant Phase 1 epilepsy; no disease-modification but seizure benefit"},
    {"drug": "L-DOPA/Carbidopa (Phase 2)", "level": "C", "tried_pct": 30, "responder_pct": 43,
     "note": "Phase 2 parkinsonism trial mandatory; partial/transient response ~40–50%"},
    {"drug": "Deferiprone (Investigational)", "level": "INV", "tried_pct": 8, "responder_pct": 50,
     "note": "Iron chelation; NBIA Research Institute trials; MRI iron reduction shown; functional benefit TBD"},
]

CONTRAINDICATIONS = [
    {"drug": "PHT (Phenytoin)", "reason": "ABSOLUTE CI — worsens myoclonus; no evidence; narrow TW; voltage-gated Na-channel blocker may increase seizure burden in mixed BPAN epilepsy"},
    {"drug": "CBZ (Carbamazepine)", "reason": "AVOID — aggravates myoclonic and absence seizures; may increase seizure burden"},
    {"drug": "OXC (Oxcarbazepine)", "reason": "AVOID — similar profile to CBZ; may worsen myoclonic-absence component"},
    {"drug": "VPA in POLG mutation carriers", "reason": "ABSOLUTE CI — fatal hepatotoxicity (Alpers syndrome); POLG panel mandatory before any VPA initiation in BPAN"},
    {"drug": "VGB > 16 weeks continuous without REMS", "reason": "ABSOLUTE CI — irreversible visual field constriction; REMS ophthalmology monitoring mandatory"},
]

# ── DDx table ──────────────────────────────────────────────────────────────
DDX = [
    {"condition": "PKAN (PANK2)", "distinguishing": "Eye-of-tiger sign GP (T2 central hyperintensity + hypointense rim); no SN predominance; dystonia > parkinsonism; pantothenate kinase defect",
     "shared": "Brain iron, neurodegeneration, NBIA family"},
    {"condition": "MPAN (C19orf12)", "distinguishing": "SN+GP+striatum iron; optic atrophy; motor neuropathy; no childhood epilepsy prominence; adult-onset mainly",
     "shared": "SN iron, parkinsonism, dementia"},
    {"condition": "Kufor-Rakeb (ATP13A2)", "distinguishing": "Juvenile parkinsonism; no childhood epilepsy; SN iron; lysosomal P5-ATPase defect",
     "shared": "SN iron, parkinsonism"},
    {"condition": "Angelman Syndrome (UBE3A)", "distinguishing": "Happy affect PATHOGNOMONIC; methylation abnormal; no parkinsonism; no NBIA iron; breathing absent",
     "shared": "ID, absent speech, epilepsy, female predominance in some cohorts"},
    {"condition": "Rett Syndrome (MECP2)", "distinguishing": "Breathing irregularity PATHOGNOMONIC; regression after normal development 6–18m; hand-wringing dominant; no iron on MRI",
     "shared": "Females, ID, epilepsy, stereotypies"},
    {"condition": "FOXG1 Syndrome", "distinguishing": "Frontal simplification/dysplasia on MRI; severe dyskinesias; no iron; congenital onset (no normal period)",
     "shared": "Profound ID, absent speech, epilepsy"},
    {"condition": "Mitochondrial Disease (POLG/MELAS/Alpers)", "distinguishing": "Elevated lactate; strokelike episodes; MRI cortical ribboning (MELAS); mtDNA depletion; mitochondrial histopathology",
     "shared": "Seizures, neurodegeneration, mitochondrial dysfunction secondary in BPAN"},
    {"condition": "Pitt-Hopkins (TCF4)", "distinguishing": "Breathing episodes (episodic hyperventilation-apnoea) PATHOGNOMONIC; beaked nose + Cupid-bow lip; no NBIA iron; no Phase 2 parkinsonism",
     "shared": "ID, absent speech, epilepsy, corpus callosum thin"},
]

# ── Key concepts (definitions) ─────────────────────────────────────────────
DEFINITIONS = [
    {"term": "BPAN (Beta-propeller protein-associated neurodegeneration)",
     "def": "X-linked dominant NBIA caused by de novo WDR45 mutations. Biphasic: childhood static encephalopathy (ID + epilepsy) → adolescent-onset rapidly progressive parkinsonism + dementia. NBIA5."},
    {"term": "WDR45 (WIPI4)",
     "def": "309-aa 7-bladed beta-propeller protein. Autophagy scaffold bridging ULK1 initiation complex to ATG2A/B elongation machinery via PI3P recognition. Expressed in all tissues; highest in brain neurons."},
    {"term": "NBIA (Neurodegeneration with Brain Iron Accumulation)",
     "def": "Group of hereditary progressive neurological disorders with pathological iron accumulation in basal ganglia (substantia nigra, globus pallidus). Includes PKAN, BPAN, MPAN, PLAN, COASY, CoPAN, Kufor-Rakeb, aceruloplasminemia, neuroferritinopathy."},
    {"term": "PI3P (Phosphatidylinositol 3-phosphate)",
     "def": "Phosphoinositide lipid generated by VPS34/PIK3C3 complex on early endosomes and phagophore initiation sites (omegasomes). WDR45/WIPI4 binds PI3P via WFDE motif → autophagosome nucleation platform."},
    {"term": "Ferritinophagy",
     "def": "Selective autophagy of ferritin-iron complexes via the cargo receptor NCOA4. WDR45 LOF impairs ferritinophagy → ferritin accumulates → labile iron pool ↑ → ferroptosis in SN/GP neurons → T2*/SWI hypointensity (BPAN MRI sign)."},
    {"term": "Phagophore Elongation (ATG2A/B Lipid Transfer)",
     "def": "ATG2A/B tethers ER membrane to growing phagophore edge; transfers phospholipids from ER to phagophore for membrane expansion. WDR45 LOF → ATG2 not recruited → stalled phagophore (incomplete autophagosome)."},
    {"term": "Substantia Nigra Iron (T2*/SWI Hypointensity)",
     "def": "Pathological iron deposition in SNr neurons (WDR45 LOF → ferritinophagy failure + ferroptosis). T2*/GRE/SWI hypointensity in SN is the MRI biomarker of BPAN. May be absent in Phase 1 childhood scans — request SWI specifically."},
    {"term": "Halo Sign (T1 BPAN)",
     "def": "T1-weighted MRI: T1 hyperintense rim surrounding T1-hypointense SN core. Specific to BPAN among NBIA syndromes. Reflects non-heme iron causing T1 shortening at halo boundary. Absent in PKAN/MPAN."},
    {"term": "Biphasic Course (BPAN Phase 1 → Phase 2)",
     "def": "BPAN hallmark: Phase 1 (childhood, years 0–10) = static encephalopathy (ID + epilepsy + no regression). Phase 2 (adolescence–adulthood, typically 15–30yr) = sudden onset rapidly progressive parkinsonism + dementia. Sudden transition distinguishes from continuous neurodegenerative disorders."},
    {"term": "X-linked Dominant (WDR45)",
     "def": "WDR45 at Xp11.23. De novo heterozygous mutations in females cause BPAN (one mutant X sufficient — dominant). Males with hemizygous WDR45 mutations are extremely rare (<10 published, 2026) — likely pre/post-zygotic mosaic or hypomorphic variants only."},
    {"term": "POLG Mandatory (BPAN)",
     "def": "POLG (mitochondrial DNA polymerase gamma) gene panel mandatory before VPA initiation in BPAN. Rationale: WDR45 LOF causes secondary mitochondrial dysfunction (mitophagy failure → ROS → mtDNA instability); undetected POLG mutations in a BPAN patient given VPA → risk of Alpers-like fatal hepatotoxicity."},
    {"term": "Deferiprone (Iron Chelation, Investigational)",
     "def": "Brain-penetrant iron chelator. Mechanism: crosses BBB → chelates labile iron pool in SN/GP → reduces ferroptosis → slows BPAN neurodegeneration. TIRCON study + NBIA Research Institute trials ongoing 2026. MRI iron reduction documented. Functional outcome data pending. DO NOT use outside trials."},
    {"term": "REM Sleep Behaviour Disorder (BPAN Phase 2)",
     "def": "Iron deposition in SN (same as Parkinson disease with dementia / DLB) causes REM sleep behaviour disorder: loss of normal REM atonia → dream enactment behaviours, vivid dreams, nightmares. Present in 65% BPAN Phase 2. Clonazepam + melatonin for symptomatic management."},
    {"term": "NBIA Research Institute",
     "def": "Patient advocacy and research organisation coordinating NBIA clinical trials globally. Maintains patient registry. Coordinates deferiprone trials for BPAN, PKAN, MPAN. Website: nbia.ca / nbiaresearch.org. Key contact for deferiprone access and trial enrolment."},
    {"term": "UKISS Protocol (IS in BPAN)",
     "def": "United Kingdom Infantile Spasm Study: ACTH + VGB combination — Level A evidence for infantile spasms. Applies to BPAN IS subgroup (25% of BPAN). VGB REMS 16-week ophthalmology monitoring mandatory for visual field monitoring."},
]

# ── Monitoring and lifecycle ───────────────────────────────────────────────
MONITORING = [
    {"item": "MRI Brain (SWI/GRE/T2* mandatory)", "frequency": "Every 2 years Phase 1; annually Phase 2",
     "rationale": "Monitor iron accumulation onset; SWI more sensitive than T2; halo sign may appear pre-symptomatic"},
    {"item": "POLG Gene Panel", "frequency": "ONCE before VPA initiation",
     "rationale": "Mitochondrial safety screen; mandatory per 2024 expert consensus"},
    {"item": "VGB REMS Ophthalmology (if VGB used)", "frequency": "Baseline + every 16 weeks",
     "rationale": "Visual field constriction monitoring — VGB REMS requirement; irreversible once established"},
    {"item": "Epilepsy Monitoring (EEG + seizure diary)", "frequency": "Annual EEG; seizure diary monthly",
     "rationale": "Track epilepsy severity, evolution to Lennox-Gastaut, Phase 2 seizure change"},
    {"item": "Neurological Assessment (Phase 2 vigilance)", "frequency": "6-monthly from age 12",
     "rationale": "Early Phase 2 detection: screen for bradykinesia, rigidity, cognitive change annually"},
    {"item": "Neuropsychological Assessment", "frequency": "Every 2–3 years Phase 1; annually Phase 2",
     "rationale": "Track cognitive trajectory; document Phase 2 dementia onset for care planning"},
    {"item": "Sleep Study (polysomnography)", "frequency": "When REM behaviour disorder suspected",
     "rationale": "Phase 2: REM sleep behaviour disorder — document, manage with clonazepam/melatonin"},
    {"item": "L-DOPA Trial (Phase 2 onset)", "frequency": "At Phase 2 onset",
     "rationale": "Trial mandatory; 40–50% partial response; establish baseline UPDRS before trial"},
    {"item": "Deferiprone Trial Enrolment Assessment", "frequency": "At Phase 2 onset",
     "rationale": "Refer to NBIA Research Institute trial network; best window for iron chelation before severe neurodegeneration"},
]

LIFECYCLE = [
    {"stage": "Neonatal–6 months", "features": "Hypotonia (universal); normal or near-normal birth; may have neonatal IS onset (rare)"},
    {"stage": "6 months–3 years", "features": "Developmental plateau: no speech milestones; motor delay; seizure onset typical (median 18m)"},
    {"stage": "3–10 years (Phase 1 stable)", "features": "Static encephalopathy; epilepsy established; autism features; minimal gains with therapy; MRI SWI often normal"},
    {"stage": "10–14 years (Pre-Phase 2 surveillance)", "features": "EEG and MRI surveillance; Phase 2 anticipatory guidance; early SWI changes may appear; no clinical deterioration"},
    {"stage": "15–25 years (Phase 2 onset)", "features": "SUDDEN parkinsonism onset (bradykinesia/rigidity first); dementia begins; dystonia; sleep disturbance; L-DOPA trial; iron chelation referral"},
    {"stage": "25–35 years (Phase 2 progression)", "features": "Rapidly progressive; severe disability; loss of ambulation; nursing care; deferiprone if on trial; palliative planning"},
    {"stage": "35+ years (Advanced Phase 2)", "features": "Severe dementia; total care dependence; spasticity + dystonia + parkinsonism combined; respiratory complications"},
]

THRESHOLDS = [
    {"parameter": "Plasma glutamate", "threshold": "NOT elevated (unlike SLC25A22)", "significance": "BPAN is NOT a metabolic disorder — no biochemical plasma biomarker"},
    {"parameter": "Plasma lactate", "threshold": "Normal or mildly ↑ secondary", "significance": "Secondary mitochondrial dysfunction; not primary; elevated only in stress/seizure"},
    {"parameter": "SWI/T2* SN hypointensity onset", "threshold": "Typically 15–30 years", "significance": "MRI iron may be ABSENT in Phase 1 scans — does NOT exclude BPAN; repeat SWI in adolescence"},
    {"parameter": "L-DOPA trial threshold", "threshold": "UPDRS baseline + 3-month trial", "significance": "Partial response (≥30% UPDRS motor improvement) in 40–50%; taper if non-responder"},
    {"parameter": "Deferiprone enrolment", "threshold": "Phase 2 onset; trial network referral", "significance": "Best therapeutic window before severe neuronal loss; contact NBIA Research Institute"},
    {"parameter": "VPA POLG safety threshold", "threshold": "POLG panel before any VPA", "significance": "Any POLG mutation → VPA ABSOLUTE CI; even heterozygous POLG variants mandate caution"},
    {"parameter": "VGB REMS visual field", "threshold": "16-week ophthalmology intervals", "significance": "Visual constriction >30° from baseline → consider VGB discontinuation"},
    {"parameter": "Phase 2 cognitive decline threshold", "threshold": ">6 points MMSE decline in 12 months", "significance": "Triggers full dementia workup; plan for care escalation"},
]

STANDARDS = [
    "NBIA Research Institute: BPAN Clinical Management Guidelines 2023",
    "ILAE 2022 Genetic Epilepsy Classification (WDR45-BPAN: DEE category)",
    "Hempel M et al. 2014: WDR45 de novo mutations (Nature Genetics — disease description)",
    "Saitsu H et al. 2013: BPAN/SENDA WDR45 mutations (Nature Genetics)",
    "TIRCON Study Group: Deferiprone in NBIA (EMA-funded, NBIA Research Institute)",
    "NICE NG217 (2022): Management of epilepsies in children and adults",
    "VGB REMS Program: FDA mandate 16-week ophthalmology monitoring",
    "POLG Expert Panel 2024: Mandatory POLG screening before VPA in autophagy/mitochondrial disorders",
]

REFERENCES = [
    "Haack TB et al. (2012). Exome sequencing reveals de novo WDR45 mutations causing a phenotypically distinct, X-linked dominant form of NBIA. Am J Hum Genet, 91(6), 1144–1149.",
    "Saitsu H et al. (2013). De novo mutations in the autophagy gene WDR45 cause static encephalopathy of childhood with neurodegeneration in adulthood. Nat Genet, 45(4), 445–449.",
    "Hempel M et al. (2014). BPAN - a clinically and radiologically distinct NBIA subtype caused by de novo WDR45 mutations. Orphanet J Rare Dis, 9, 147.",
    "Hayflick SJ et al. (2013). Beta-propeller protein-associated neurodegeneration: a new X-linked dominant disorder with brain iron accumulation. Brain, 136(Pt 6), 1708–1717.",
    "NBIA Research Institute (2023). BPAN Clinical Management Guidelines. nbia.ca.",
    "Wan H et al. (2020). Ferritinophagy via NCOA4 is required for the regulation of iron homeostasis. Nat Commun, 11(1), 5708.",
]


def _patients():
    """Generate 40 synthetic BPAN patients (seed-515)."""
    pts = []
    etio_pool = (
        ["truncating"] * 30 + ["missense"] * 6 + ["splice"] * 3 + ["cnv"] * 1
    )
    RNG.shuffle(etio_pool)

    aed_options = ["LEV", "VPA", "CLB", "ZNS", "TPM", "RFN", "KD", "ACTH+VGB"]
    seizure_options = ["focal", "absence", "gtcs", "myoclonic", "infantile_spasms",
                       "atonic", "epileptic_spasms", "tonic"]

    for i in range(N):
        sex = "F" if i < N_FEMALE else "M"
        etio = etio_pool[i]

        # Severity by etiology
        if etio in ("truncating", "cnv"):
            id_level = RNG.choice(["profound"] * 4 + ["severe"])
            speech = RNG.choice(["absent"] * 4 + ["<5 words"])
            onset_mo = RNG.randint(1, 30)
            drug_resistant = RNG.random() < 0.80
        elif etio == "missense":
            id_level = RNG.choice(["profound", "severe", "moderate"])
            speech = RNG.choice(["absent"] * 2 + ["<5 words", "10-20 words"])
            onset_mo = RNG.randint(6, 48)
            drug_resistant = RNG.random() < 0.65
        else:  # splice
            id_level = RNG.choice(["moderate", "severe"])
            speech = RNG.choice(["<5 words", "10-20 words", "absent"])
            onset_mo = RNG.randint(12, 60)
            drug_resistant = RNG.random() < 0.55

        # Seizure types
        s_types = []
        for stype in seizure_options:
            probs = {
                "focal": 0.80, "absence": 0.60, "gtcs": 0.50,
                "myoclonic": 0.40, "infantile_spasms": 0.25,
                "atonic": 0.20, "epileptic_spasms": 0.15, "tonic": 0.12
            }
            if RNG.random() < probs[stype]:
                s_types.append(stype)
        if not s_types:
            s_types = ["focal"]

        n_aeds = RNG.randint(2, 6) if drug_resistant else RNG.randint(1, 3)
        aeds_tried = RNG.sample(aed_options, min(n_aeds, len(aed_options)))

        # MRI features
        corpus_callosum_thin = RNG.random() < 0.55
        phase2 = RNG.random() < 0.30  # 30% adults in cohort are in Phase 2
        sn_iron = RNG.random() < (0.90 if phase2 else 0.10)  # iron visible mainly Phase 2
        halo_sign = sn_iron and RNG.random() < 0.65

        polg_tested = RNG.random() < 0.75
        autism_features = RNG.random() < 0.65
        happy_affect = RNG.random() < 0.15  # unlike Angelman, NOT dominant
        hand_stereotypies = RNG.random() < 0.35

        phase2_parkinsonism = phase2 and RNG.random() < 0.90
        ldopa_tried = phase2 and RNG.random() < 0.80
        ldopa_response = ldopa_tried and RNG.random() < 0.45

        current_age = RNG.randint(4, 45)
        seizure_free = RNG.random() < 0.12  # few achieve freedom

        pts.append({
            "id": f"BPAN-{i+1:03d}",
            "sex": sex,
            "etiology": etio,
            "id_level": id_level,
            "speech": speech,
            "onset_months": onset_mo,
            "seizure_types": s_types,
            "n_seizure_types": len(s_types),
            "drug_resistant": drug_resistant,
            "n_aeds_tried": n_aeds,
            "aeds_tried": aeds_tried,
            "corpus_callosum_thin": corpus_callosum_thin,
            "sn_iron_mri": sn_iron,
            "halo_sign_t1": halo_sign,
            "phase2": phase2,
            "phase2_parkinsonism": phase2_parkinsonism,
            "ldopa_tried": ldopa_tried,
            "ldopa_response": ldopa_response,
            "autism_features": autism_features,
            "happy_affect": happy_affect,
            "hand_stereotypies": hand_stereotypies,
            "polg_tested": polg_tested,
            "seizure_free": seizure_free,
            "current_age": current_age,
        })
    return pts


_CACHE = {}


def _get_patients():
    if "pts" not in _CACHE:
        _CACHE["pts"] = _patients()
    return _CACHE["pts"]


def get_overview():
    pts = _get_patients()
    n = len(pts)

    def pct(cond): return round(sum(1 for p in pts if cond(p)) / n * 100)

    kpis = {
        "n_patients": n,
        "n_female": sum(1 for p in pts if p["sex"] == "F"),
        "n_male": sum(1 for p in pts if p["sex"] == "M"),
        "focal_pct": pct(lambda p: "focal" in p["seizure_types"]),
        "absence_pct": pct(lambda p: "absence" in p["seizure_types"]),
        "gtcs_pct": pct(lambda p: "gtcs" in p["seizure_types"]),
        "myoclonic_pct": pct(lambda p: "myoclonic" in p["seizure_types"]),
        "infantile_spasms_pct": pct(lambda p: "infantile_spasms" in p["seizure_types"]),
        "atonic_pct": pct(lambda p: "atonic" in p["seizure_types"]),
        "drug_resistant_pct": pct(lambda p: p["drug_resistant"]),
        "absent_speech_pct": pct(lambda p: p["speech"] == "absent"),
        "profound_id_pct": pct(lambda p: p["id_level"] == "profound"),
        "corpus_callosum_thin_pct": pct(lambda p: p["corpus_callosum_thin"]),
        "sn_iron_pct": pct(lambda p: p["sn_iron_mri"]),
        "halo_sign_pct": pct(lambda p: p["halo_sign_t1"]),
        "autism_pct": pct(lambda p: p["autism_features"]),
        "happy_affect_pct": pct(lambda p: p["happy_affect"]),
        "phase2_pct": pct(lambda p: p["phase2"]),
        "parkinsonism_pct": pct(lambda p: p["phase2_parkinsonism"]),
        "ldopa_tried_pct": pct(lambda p: p["ldopa_tried"]),
        "polg_tested_pct": pct(lambda p: p["polg_tested"]),
        "seizure_free_pct": pct(lambda p: p["seizure_free"]),
        "mean_aeds_tried": round(sum(p["n_aeds_tried"] for p in pts) / n, 1),
        "mean_onset_months": round(sum(p["onset_months"] for p in pts) / n, 1),
    }

    return {
        "disease": "WDR45 BPAN (Beta-propeller protein-associated neurodegeneration / NBIA5)",
        "gene": "WDR45 (WIPI4)", "chromosome": "Xp11.23",
        "omim_gene": "300526", "omim_disease": "300643",
        "inheritance": "X-linked Dominant — De Novo in Females; Hemizygous Males Extremely Rare",
        "cohort_n": n, "seed": SEED,
        "kpis": kpis,
        "etiology_distribution": ETIOLOGIES,
        "treatments_summary": [
            {"drug": t["drug"], "level": t["level"],
             "tried_pct": t["tried_pct"], "responder_pct": t["responder_pct"]}
            for t in TREATMENTS
        ],
        "contraindications_summary": [
            {"drug": c["drug"], "reason": c["reason"][:80] + "…"} for c in CONTRAINDICATIONS
        ],
        "monitoring_summary": [
            {"item": m["item"], "frequency": m["frequency"]} for m in MONITORING
        ],
        "lifecycle": [
            {"stage": l["stage"], "features": l["features"][:100]} for l in LIFECYCLE
        ],
        "thresholds": THRESHOLDS,
        "clinical_highlights": [
            "BIPHASIC: childhood static encephalopathy → SUDDEN adolescent-onset parkinsonism + dementia",
            "90% females (X-linked dominant de novo); hemizygous males extremely rare",
            "MRI SWI/T2*: substantia nigra hypointensity + 'halo sign' T1 = PATHOGNOMONIC for BPAN",
            "MRI iron may be ABSENT in Phase 1 childhood scans — does NOT exclude BPAN; repeat SWI in adolescence",
            "POLG MANDATORY before VPA (secondary mitochondrial dysfunction → hepatotoxicity risk)",
            "PHT/CBZ/OXC: AVOID (aggravate myoclonus; worsen mixed epilepsy)",
            "Deferiprone (iron chelation): investigational — refer to NBIA Research Institute trials",
            "L-DOPA trial mandatory at Phase 2 onset (40–50% partial response)",
        ],
        "ddx_table": DDX,
        "tier_summary": {
            "disease_group": "NBIA (Neurodegeneration with Brain Iron Accumulation)",
            "epilepsy_classification": "Developmental and Epileptic Encephalopathy (DEE) / NBIA5",
            "precision_therapy": "None approved 2026 (deferiprone investigational)",
            "iron_chelation": "Investigational — NBIA Research Institute trial referral",
            "key_biomarker": "MRI SWI/T2* hypointensity substantia nigra + globus pallidus",
        },
        "standards": STANDARDS,
    }


def get_breakdown():
    pts = _get_patients()

    # Etiology breakdown with patient details
    etio_breakdown = []
    for etio_key, label in [
        ("truncating", "Truncating/Frameshift (Null)"),
        ("missense", "Missense (beta-propeller interface)"),
        ("splice", "Splice Site (partial exon skip)"),
        ("cnv", "Large Deletion/CNV"),
    ]:
        group = [p for p in pts if p["etiology"] == etio_key]
        if not group:
            continue
        n_g = len(group)
        etio_breakdown.append({
            "etiology": label,
            "n": n_g,
            "pct": round(n_g / len(pts) * 100),
            "drug_resistant_pct": round(sum(1 for p in group if p["drug_resistant"]) / n_g * 100),
            "absent_speech_pct": round(sum(1 for p in group if p["speech"] == "absent") / n_g * 100),
            "phase2_pct": round(sum(1 for p in group if p["phase2"]) / n_g * 100),
            "sn_iron_pct": round(sum(1 for p in group if p["sn_iron_mri"]) / n_g * 100),
            "mean_onset_mo": round(sum(p["onset_months"] for p in group) / n_g, 1),
            "mean_aeds": round(sum(p["n_aeds_tried"] for p in group) / n_g, 1),
        })

    # Seizure type breakdown
    seizure_breakdown = []
    for st in ["focal", "absence", "gtcs", "myoclonic", "infantile_spasms",
               "atonic", "epileptic_spasms", "tonic"]:
        group = [p for p in pts if st in p["seizure_types"]]
        seizure_breakdown.append({
            "type": st.replace("_", " ").title(),
            "n": len(group),
            "pct": round(len(group) / len(pts) * 100),
            "drug_resistant_pct": round(sum(1 for p in group if p["drug_resistant"]) / max(len(group), 1) * 100),
        })

    # Per-patient summary (first 40)
    per_patient = []
    for p in pts:
        per_patient.append({
            "id": p["id"],
            "sex": p["sex"],
            "etiology": p["etiology"],
            "onset_mo": p["onset_months"],
            "seizure_types": ", ".join(p["seizure_types"][:3]),
            "drug_resistant": p["drug_resistant"],
            "n_aeds": p["n_aeds_tried"],
            "absent_speech": p["speech"] == "absent",
            "id_level": p["id_level"],
            "corpus_callosum_thin": p["corpus_callosum_thin"],
            "sn_iron": p["sn_iron_mri"],
            "halo_sign": p["halo_sign_t1"],
            "phase2": p["phase2"],
            "parkinsonism": p["phase2_parkinsonism"],
            "autism": p["autism_features"],
            "polg_tested": p["polg_tested"],
            "seizure_free": p["seizure_free"],
        })

    # Treatment summary
    treatment_summary = []
    for t in TREATMENTS:
        treatment_summary.append({
            "drug": t["drug"],
            "level": t["level"],
            "tried_pct": t["tried_pct"],
            "responder_pct": t["responder_pct"],
            "note": t["note"],
        })

    return {
        "cohort_n": len(pts),
        "etiology_breakdown": etio_breakdown,
        "seizure_breakdown": seizure_breakdown,
        "per_patient": per_patient,
        "treatment_summary": treatment_summary,
        "contraindications": CONTRAINDICATIONS,
        "ddx_table": DDX,
        "monitoring": MONITORING,
        "lifecycle": LIFECYCLE,
        "thresholds": THRESHOLDS,
        "standards": STANDARDS,
        "references": REFERENCES,
    }


def get_definitions():
    return {
        "disease": "WDR45 BPAN (Beta-propeller protein-associated neurodegeneration / NBIA5)",
        "gene": "WDR45 (WIPI4) — Xp11.23 — OMIM 300526",
        "omim_disease": "300643",
        "definitions": DEFINITIONS,
        "contraindications": CONTRAINDICATIONS,
        "standards": STANDARDS,
        "references": REFERENCES,
        "key_concepts": [d["term"] for d in DEFINITIONS],
    }
